var database = database || {};

database.html = [
    { q: "¿Qué etiqueta contiene los metadatos y enlaces a hojas de estilo?", options: ["<body>", "<meta>", "<head>", "<html>"], correct: 2 },
    { q: "¿Cuál es el propósito de <!DOCTYPE html>?", options: ["Definir el título", "Indicar que es HTML5", "Crear un comentario", "Cerrar el documento"], correct: 1 },
    { q: "¿Qué etiqueta se usa para el título de la pestaña del navegador?", options: ["<header>", "<h1>", "<title>", "<head>"], correct: 2 },
    { q: "¿Cuál es la etiqueta raíz de todo documento HTML?", options: ["<body>", "<html>", "<head>", "<root>"], correct: 1 },
    { q: "¿Qué etiqueta se usa para un salto de línea?", options: ["<hr>", "<lb>", "<break>", "<br>"], correct: 3 },
    { q: "¿Para qué sirve la etiqueta <nav>?", options: ["Navegación", "Gráficos", "Párrafos", "Tablas"], correct: 0 },
    { q: "¿Qué etiqueta define el cuerpo visible de la web?", options: ["<main>", "<body>", "<section>", "<div>"], correct: 1 },
    { q: "¿Cómo se define un encabezado de nivel máximo?", options: ["<h6>", "<head>", "<header>", "<h1>"], correct: 3 },
    { q: "¿Qué etiqueta se usa para una lista desordenada?", options: ["<ul>", "<ol>", "<li>", "<list>"], correct: 0 },
    { q: "¿Qué etiqueta define un elemento dentro de una lista?", options: ["<ul>", "<list>", "<li>", "<ol>"], correct: 2 },
    { q: "¿Qué atributo se usa para la URL de una imagen?", options: ["href", "link", "url", "src"], correct: 3 },
    { q: "¿Qué atributo de <a> abre un enlace en otra pestaña?", options: ["target='_blank'", "target='_new'", "rel='external'", "href='new'"], correct: 0 },
    { q: "¿Para qué sirve el atributo 'alt' en <img>?", options: ["Tamaño", "Título", "Texto alternativo", "Borde"], correct: 2 },
    { q: "¿Qué etiqueta se usa para un formulario?", options: ["<input>", "<form>", "<fieldset>", "<select>"], correct: 1 },
    { q: "¿Cuál es la etiqueta para una celda de encabezado de tabla?", options: ["<tr>", "<td>", "<th>", "<table>"], correct: 2 },
    { q: "¿Qué etiqueta de HTML5 representa contenido independiente?", options: ["<section>", "<div>", "<article>", "<aside>"], correct: 2 },
    { q: "¿Para qué sirve la etiqueta <footer>?", options: ["Cabecera", "Pie de página", "Menú lateral", "Sección principal"], correct: 1 },
    { q: "¿Qué etiqueta se usa para agrupar opciones en un <select>?", options: ["<option>", "<group>", "<optgroup>", "<list>"], correct: 2 },
    { q: "¿Cómo se sube un nivel en una ruta relativa?", options: ["./", "/", "../", "up/"], correct: 2 },
    { q: "¿Qué etiqueta se usa para una lista ordenada?", options: ["<ul>", "<ol>", "<li>", "<list>"], correct: 1 },
    { q: "¿Qué atributo define un identificador único?", options: ["class", "id", "name", "key"], correct: 1 },
    { q: "¿Qué etiqueta se usa para texto en cursiva (énfasis)?", options: ["<b>", "<strong>", "<i>", "<em>"], correct: 3 },
    { q: "¿Qué etiqueta se usa para texto en negrita (importancia)?", options: ["<strong>", "<em>", "<i>", "<neg>"], correct: 0 },
    { q: "¿Cuál es el protocolo seguro para URLs?", options: ["HTTP", "FTP", "HTTPS", "SMTP"], correct: 2 },
    { q: "¿Qué etiqueta define un campo de entrada de texto?", options: ["<input>", "<textarea>", "<select>", "<button>"], correct: 0 },
    { q: "¿Qué etiqueta define un área de texto multilínea?", options: ["<input>", "<textarea>", "<text>", "<form>"], correct: 1 },
    { q: "¿Qué etiqueta se usa para un botón?", options: ["<input>", "<submit>", "<button>", "<press>"], correct: 2 },
    { q: "¿Qué etiqueta representa contenido relacionado (tangencial)?", options: ["<section>", "<article>", "<aside>", "<nav>"], correct: 2 },
    { q: "¿Qué etiqueta se usa para insertar un video?", options: ["<media>", "<video>", "<movie>", "<source>"], correct: 1 },
    { q: "¿Cómo se llama al lenguaje basado en etiquetas como HTML?", options: ["Programación", "Marcado", "Estilos", "Scripting"], correct: 1 },
    { q: "¿Qué atributo se usa para que un campo de formulario sea obligatorio?", options: ["required", "validate", "needed", "must"], correct: 0 },
    { q: "¿Qué etiqueta se usa para incrustar un archivo de audio?", options: ["<sound>", "<music>", "<audio>", "<media>"], correct: 2 },
    { q: "¿Qué etiqueta se usa para definir una leyenda para un <fieldset>?", options: ["<label>", "<caption>", "<title>", "<legend>"], correct: 3 },
    { q: "¿Qué etiqueta HTML5 se usa para dibujar gráficos mediante scripts (JS)?", options: ["<svg>", "<canvas>", "<paint>", "<graphics>"], correct: 1 },
    { q: "¿Qué atributo de <input> limita los caracteres permitidos usando una expresión regular?", options: ["regex", "validate", "pattern", "rule"], correct: 2 },
    { q: "¿Qué etiqueta se usa para agrupar elementos de un formulario?", options: ["<group>", "<fieldset>", "<section>", "<area>"], correct: 1 },
    { q: "¿Qué valor de 'type' en <input> permite seleccionar un color?", options: ["palette", "hex", "rgb", "color"], correct: 3 },
    { q: "¿Qué etiqueta define una lista de opciones predefinidas para un <input>?", options: ["<select>", "<datalist>", "<options>", "<list>"], correct: 1 },
    { q: "¿Qué atributo se usa para asociar un <label> con un <input>?", options: ["id", "name", "for", "rel"], correct: 2 },
    { q: "¿Qué etiqueta se usa para mostrar el progreso de una tarea?", options: ["<step>", "<bar>", "<loading>", "<progress>"], correct: 3 },
    { q: "¿Qué etiqueta se utiliza para resaltar texto (fondo amarillo por defecto)?", options: ["<mark>", "<highlight>", "<color>", "<span>"], correct: 0 },
    { q: "¿Qué etiqueta se usa para representar el resultado de un cálculo?", options: ["<result>", "<output>", "<calc>", "<math>"], correct: 1 },
    { q: "¿Cuál es la etiqueta correcta para definir una descripción o pie de una imagen?", options: ["<legend>", "<caption>", "<figcaption>", "<label>"], correct: 2 },
    { q: "¿Qué contenedor se usa para agrupar una imagen y su descripción?", options: ["<figure>", "<imagegroup>", "<media>", "<section>"], correct: 0 },
    { q: "¿Qué atributo permite que un elemento sea editable por el usuario?", options: ["editable", "contenteditable", "useredit", "modify"], correct: 1 },
    { q: "¿Qué etiqueta define un rango numérico (slider)?", options: ["<input type='slider'>", "<input type='range'>", "<input type='number'>", "<range>"], correct: 1 },
    { q: "¿Qué etiqueta se usa para definir una tabla?", options: ["<grid>", "<tab>", "<table>", "<list>"], correct: 2 },
    { q: "¿Qué etiqueta define una fila de una tabla?", options: ["<td>", "<th>", "<row>", "<tr>"], correct: 3 },
    { q: "¿Qué etiqueta define una celda de datos estándar en una tabla?", options: ["<td>", "<th>", "<data>", "<tr>"], correct: 0 },
    { q: "¿Qué etiqueta se usa para agrupar el contenido del cuerpo de una tabla?", options: ["<thead>", "<tfoot>", "<tbody>", "<table-body>"], correct: 2 },
    { q: "¿Qué etiqueta se usa para el encabezado de una tabla?", options: ["<top>", "<thead>", "<header>", "<th>"], correct: 1 },
    { q: "¿Qué atributo de celda permite expandirla a través de varias columnas?", options: ["rowspan", "colspan", "width", "scope"], correct: 1 },
    { q: "¿Qué atributo de celda permite expandirla a través de varias filas?", options: ["rowspan", "colspan", "height", "scope"], correct: 0 },
    { q: "¿Qué etiqueta se usa para añadir una descripción breve (tooltip) al pasar el ratón?", options: ["alt", "desc", "info", "title"], correct: 3 },
    { q: "¿Qué etiqueta se usa para representar código de programación?", options: ["<source>", "<code>", "<script>", "<pre>"], correct: 1 },
    { q: "¿Qué etiqueta mantiene los espacios y saltos de línea del texto original?", options: ["<text>", "<p>", "<pre>", "<code>"], correct: 2 },
    { q: "¿Qué etiqueta define una cita corta en línea?", options: ["<cite>", "<blockquote>", "<q>", "<quote>"], correct: 2 },
    { q: "¿Qué etiqueta define una sección de cita larga o bloque?", options: ["<q>", "<quote>", "<section>", "<blockquote>"], correct: 3 },
    { q: "¿Qué etiqueta se usa para definir información de contacto en un documento?", options: ["<contact>", "<address>", "<footer>", "<meta>"], correct: 1 },
    { q: "¿Qué etiqueta define un hipervínculo?", options: ["<link>", "<a>", "<url>", "<href>"], correct: 1 },
    { q: "¿Qué atributo especifica el idioma de la página web?", options: ["lang", "xml:lang", "language", "charset"], correct: 0 },
    { q: "¿Qué etiqueta se usa para incluir scripts de JavaScript?", options: ["<js>", "<scripting>", "<script>", "<javascript>"], correct: 2 },
    { q: "¿Qué etiqueta se usa para definir estilos CSS internos?", options: ["<css>", "<style>", "<link>", "<design>"], correct: 1 },
    { q: "¿Qué etiqueta de HTML5 se usa para detalles que el usuario puede abrir/cerrar?", options: ["<summary>", "<details>", "<accordion>", "<section>"], correct: 1 },
    { q: "¿Qué etiqueta define el título visible de un elemento <details>?", options: ["<title>", "<header>", "<label>", "<summary>"], correct: 3 },
    { q: "¿Qué atributo de <input> especifica un valor sugerido que desaparece al escribir?", options: ["value", "hint", "placeholder", "text"], correct: 2 },
    { q: "¿Qué atributo permite subir múltiples archivos en un <input type='file'>?", options: ["multi", "multiple", "array", "all"], correct: 1 },
    { q: "¿Qué valor de 'type' se usa para campos de contraseña?", options: ["secret", "hidden", "password", "lock"], correct: 2 },
    { q: "¿Qué etiqueta se usa para marcar texto tachado (ya no correcto)?", options: ["<strike>", "<del>", "<s>", "<remove>"], correct: 1 },
    { q: "¿Qué etiqueta se usa para insertar texto que ha sido añadido recientemente?", options: ["<add>", "<new>", "<ins>", "<strong>"], correct: 2 },
    { q: "¿Qué etiqueta se utiliza para subíndices?", options: ["<sub>", "<sup>", "<below>", "<low>"], correct: 0 },
    { q: "¿Qué etiqueta se utiliza para superíndices?", options: ["<sub>", "<sup>", "<above>", "<top>"], correct: 1 },
    { q: "¿Qué atributo de <iframe> elimina el borde?", options: ["border='0'", "frameborder='0'", "noborder", "style='none'"], correct: 1 },
    { q: "¿Qué etiqueta se usa para insertar otra página web dentro de la actual?", options: ["<embed>", "<object>", "<iframe>", "<frame>"], correct: 2 },
    { q: "¿Qué atributo de <meta> define la codificación de caracteres (ej. UTF-8)?", options: ["content", "http-equiv", "charset", "encoding"], correct: 2 },
    { q: "¿Cuál es el valor predeterminado del atributo 'method' en un <form>?", options: ["POST", "PUT", "SEND", "GET"], correct: 3 },
    { q: "¿Qué atributo de un formulario define a dónde se envían los datos?", options: ["target", "action", "link", "route"], correct: 1 },
    { q: "¿Qué etiqueta define una abreviatura o acrónimo?", options: ["<abbr>", "<acr>", "<short>", "<span>"], correct: 0 },
    { q: "¿Qué etiqueta se usa para definir un botón de envío en un formulario?", options: ["<input type='button'>", "<input type='submit'>", "<input type='send'>", "<button type='go'>"], correct: 1 },
    { q: "¿Qué atributo de <input> permite solo números?", options: ["type='int'", "type='digit'", "type='number'", "type='range'"], correct: 2 },
    { q: "¿Qué etiqueta HTML se usa para dibujar gráficos vectoriales?", options: ["<canvas>", "<svg>", "<vml>", "<graphics>"], correct: 1 },
    { q: "¿Qué atributo de <img> mejora el rendimiento cargando la imagen solo cuando es visible?", options: ["loading='lazy'", "defer", "async", "cache='none'"], correct: 0 },
    { q: "¿Qué etiqueta se usa para indicar una medida dentro de un rango conocido (ej. uso de disco)?", options: ["<progress>", "<range>", "<meter>", "<gauge>"], correct: 2 },
    { q: "¿Qué etiqueta define el tiempo o una fecha?", options: ["<date>", "<time>", "<calendar>", "<moment>"], correct: 1 },
    { q: "¿Qué atributo se usa en <ol> para empezar la lista en un número específico?", options: ["begin", "index", "start", "value"], correct: 2 },
    { q: "¿Qué etiqueta se usa para definir un área dentro de un mapa de imagen?", options: ["<point>", "<area>", "<coord>", "<link>"], correct: 1 },
    { q: "¿Qué etiqueta agrupa los enlaces de navegación?", options: ["<menu>", "<nav>", "<links>", "<header>"], correct: 1 },
    { q: "¿Qué atributo de <script> hace que se ejecute en paralelo mientras se carga la página?", options: ["defer", "async", "wait", "parallel"], correct: 1 },
    { q: "¿Qué atributo de <script> hace que se ejecute solo después de que la página se haya cargado?", options: ["defer", "async", "after", "end"], correct: 0 },
    { q: "¿Qué etiqueta define la parte más importante o central del contenido?", options: ["<section>", "<article>", "<main>", "<body>"], correct: 2 },

    // KAHOOT
    { q: "¿Qué meta habilita diseño responsive?", options: ["viewport", "keyboard", "robots", "author"], correct: 0 },
    { q: "¿Qué unidad es relativa al contendor?", options: ["px", "cm", "%", "in"], correct: 2 },
    { q: "¿Qué etiqueta define navegación principal?", options: ["nav", "aside", "section", "figure"], correct: 0 },
    { q: "¿Qué atributo almacena datos personalizados?", options: ["data-*", "src", "alt", "href"], correct: 0 },
     { q: "¿Por qué usar elementos semánticos?(2 válidas)", options: ["Aleatorio", "SEO", "Decoración", "Accesibilidad"], correct: [1, 3] }
   




];