var database = database || {};

database.css = [
    { q: "¿Qué propiedad cambia el color del texto?", options: ["background-color", "color", "text-color", "font-color"], correct: 1 },
    { q: "¿Qué propiedad cambia el fondo?", options: ["color", "bg-color", "background-color", "fill"], correct: 2 },
    { q: "¿Cómo se selecciona una clase en CSS?", options: ["#clase", ".clase", "clase:", "*clase"], correct: 1 },
    { q: "¿Cómo se selecciona un ID en CSS?", options: [".id", "*id", "#id", "@id"], correct: 2 },
    { q: "¿Qué propiedad define el tamaño de la fuente?", options: ["text-size", "font-size", "font-weight", "size"], correct: 1 },
    { q: "¿Qué propiedad pone el texto en negrita?", options: ["font-style", "text-bold", "font-weight: bold", "font-size"], correct: 2 },
    { q: "¿Cuál es el valor por defecto de 'position'?", options: ["relative", "absolute", "fixed", "static"], correct: 3 },
    { q: "¿Qué propiedad añade espacio dentro del borde?", options: ["margin", "padding", "border", "spacing"], correct: 1 },
    { q: "¿Qué propiedad añade espacio fuera del borde?", options: ["padding", "spacing", "margin", "border"], correct: 2 },
    { q: "¿Qué propiedad cambia el tipo de letra?", options: ["font-family", "font-style", "text-type", "font-weight"], correct: 0 },
    { q: "¿Qué selector aplica estilos a TODOS los elementos?", options: ["#", ".", "*", "all"], correct: 2 },
    { q: "¿Cómo se comenta en CSS?", options: ["//", "/* */", "", "#"], correct: 1 },
    { q: "¿Qué propiedad quita el subrayado de los enlaces?", options: ["text-style", "text-decoration", "border: none", "text-transform"], correct: 1 },
    { q: "¿Qué hace 'display: none'?", options: ["Oculta y quita el espacio", "Oculta pero deja el hueco", "Cambia el color", "Vuelve el texto invisible"], correct: 0 },
    { q: "¿Qué propiedad controla el grosor del borde?", options: ["border-style", "border-width", "border-color", "thickness"], correct: 1 },
    { q: "¿Qué propiedad redondea las esquinas?", options: ["border-circle", "border-round", "border-radius", "corner-radius"], correct: 2 },
    { q: "¿Qué valor centra un bloque con 'margin'?", options: ["center", "middle", "auto", "0px"], correct: 2 },
    { q: "¿Qué propiedad alinea el texto?", options: ["text-align", "align-content", "vertical-align", "text-center"], correct: 0 },
    { q: "¿Qué selector elige a los párrafos dentro de un div?", options: ["div+p", "div p", "div.p", "div#p"], correct: 1 },
    { q: "¿Qué selector elige solo hijos directos?", options: ["div p", "div + p", "div > p", "div ~ p"], correct: 2 },
    { q: "¿Qué propiedad cambia el cursor al pasar por encima?", options: ["mouse", "pointer", "cursor", "hover"], correct: 2 },
    { q: "¿Qué pseudoclase se activa al pasar el ratón?", options: [":active", ":focus", ":link", ":hover"], correct: 3 },
    { q: "¿Cuál es la prioridad más alta de estilo?", options: ["Externo", "Interno", "Atributo style", "Navegador"], correct: 2 },
    { q: "¿Qué propiedad controla la transparencia?", options: ["visible", "opacity", "filter", "display"], correct: 1 },
    { q: "¿Qué unidad es relativa al tamaño de la fuente base?", options: ["px", "rem", "pt", "cm"], correct: 1 },
    { q: "¿Qué propiedad controla el espacio entre líneas?", options: ["line-height", "letter-spacing", "word-spacing", "spacing"], correct: 0 },
    { q: "¿Para qué sirve z-index?", options: ["Zoom", "Orden de capas", "Ancho", "Velocidad"], correct: 1 },
    { q: "¿Qué propiedad transforma texto a mayúsculas?", options: ["text-style", "font-variant", "text-transform", "upper"], correct: 2 },
    { q: "¿Qué modelo de caja incluye el padding en el ancho?", options: ["content-box", "border-box", "padding-box", "flex-box"], correct: 1 },
    { q: "¿Qué propiedad crea una sombra en el texto?", options: ["box-shadow", "shadow-text", "text-shadow", "font-shadow"], correct: 2 },
    { q: "¿Cómo se llama el archivo donde se guardan los estilos externos?", options: ["style.html", "hoja.css", "estilos.txt", "format.js"], correct: 1 },
    { q: "¿Qué etiqueta HTML se usa para enlazar un archivo CSS externo?", options: ["<script>", "<css>", "<style>", "<link>"], correct: 3 },
    { q: "¿Qué atributo de la etiqueta <link> especifica que es una hoja de estilo?", options: ["type='text/css'", "rel='stylesheet'", "href='style.css'", "media='all'"], correct: 1 },
    { q: "¿Cuál es la sintaxis correcta para declarar una regla CSS?", options: ["selector: {propiedad=valor}", "selector {propiedad: valor;}", "selector [propiedad: valor]", "{selector; propiedad: valor}"], correct: 1 },
    { q: "¿Qué propiedad se usa para poner el texto en cursiva?", options: ["font-style: italic", "font-weight: italic", "text-decoration: italic", "font-italic"], correct: 0 },
    { q: "¿Qué propiedad permite que el texto aparezca en versalitas?", options: ["text-transform", "font-variant", "font-weight", "font-style"], correct: 1 },
    { q: "¿Qué valor de 'text-transform' pone la primera letra de cada palabra en mayúscula?", options: ["uppercase", "lowercase", "capitalize", "initial"], correct: 2 },
    { q: "¿Qué propiedad controla el espacio entre letras?", options: ["word-spacing", "line-height", "letter-spacing", "text-spacing"], correct: 2 },
    { q: "¿Qué propiedad permite añadir una sombra a un contenedor (caja)?", options: ["text-shadow", "box-shadow", "shadow-style", "element-shadow"], correct: 1 },
    { q: "¿Qué propiedad define si un fondo se desplaza o queda fijo?", options: ["background-attachment", "background-fixed", "background-scroll", "background-repeat"], correct: 0 },
    { q: "¿Qué valor de 'background-repeat' evita que la imagen se repita?", options: ["repeat-x", "repeat-y", "no-repeat", "fixed"], correct: 2 },
    { q: "¿Cuál es el orden correcto del 'shorthand' de la propiedad border?", options: ["color style width", "width style color", "style width color", "width color style"], correct: 1 },
    { q: "¿Cómo se define un color usando el sistema decimal de rojo, verde y azul?", options: ["color: #FF0000", "color: rgb(255, 0, 0)", "color: red", "color: hsl(0, 100%, 50%)"], correct: 1 },
    { q: "¿Qué valor en RGB indica total transparencia si usamos RGBA?", options: ["1", "100", "0", "255"], correct: 2 },
    { q: "¿Qué propiedad define el orden de apilamiento (capas) de elementos posicionados?", options: ["layer-index", "stack-order", "z-index", "position-depth"], correct: 2 },
    { q: "¿Qué tipo de posicionamiento mueve el elemento respecto a su posición original?", options: ["static", "absolute", "fixed", "relative"], correct: 3 },
    { q: "¿Qué posicionamiento deja el elemento fijo aunque se haga scroll?", options: ["relative", "absolute", "fixed", "sticky"], correct: 2 },
    { q: "¿Un elemento con 'position: absolute' se posiciona respecto a...?", options: ["El navegador", "Su padre posicionado", "El elemento anterior", "El centro"], correct: 1 },
    { q: "¿Qué propiedad CSS se usa para que un elemento flote a la izquierda?", options: ["align: left", "float: left", "display: left", "position: left"], correct: 1 },
    { q: "¿Qué propiedad se usa para cancelar el efecto de un 'float' anterior?", options: ["stop", "float: none", "clear", "break"], correct: 2 },
    { q: "¿Qué propiedad activa el modelo de diseño Flexible Box?", options: ["display: flex", "display: grid", "flex: true", "box-model: flex"], correct: 0 },
    { q: "¿Qué propiedad de Flexbox cambia la dirección de los elementos a vertical?", options: ["flex-wrap", "justify-content", "flex-direction", "align-items"], correct: 2 },
    { q: "¿Qué propiedad de Flexbox alinea elementos en el eje principal (horizontal por defecto)?", options: ["align-items", "justify-content", "align-content", "flex-flow"], correct: 1 },
    { q: "¿Qué propiedad de Flexbox alinea elementos en el eje secundario (vertical por defecto)?", options: ["justify-content", "align-items", "flex-direction", "order"], correct: 1 },
    { q: "¿Qué valor de 'flex-direction' invierte el orden de los elementos?", options: ["reverse", "row-reverse", "inverse", "back"], correct: 1 },
    { q: "¿Qué propiedad permite que los elementos flex salten a la siguiente línea?", options: ["flex-line", "flex-wrap", "flex-flow", "flex-break"], correct: 1 },
    { q: "¿Qué propiedad cambia el orden visual de un hijo dentro de un contenedor flex?", options: ["index", "z-index", "order", "flex-order"], correct: 2 },
    { q: "¿Qué propiedad se usa para definir el ancho máximo de un elemento?", options: ["width-max", "max-width", "limit-width", "box-width"], correct: 1 },
    { q: "¿Qué propiedad controla el desbordamiento de contenido en una caja?", options: ["overflow", "scroll", "hidden", "display"], correct: 0 },
    { q: "¿Qué valor de 'overflow' oculta el contenido que se sale de la caja?", options: ["scroll", "visible", "auto", "hidden"], correct: 3 },
    { q: "¿Qué pseudoclase se aplica a un enlace que ya ha sido pulsado?", options: [":hover", ":active", ":visited", ":link"], correct: 2 },
    { q: "¿Qué pseudoclase selecciona el primer hijo de un elemento?", options: [":first-child", ":last-child", ":only-child", ":nth-child(0)"], correct: 0 },
    { q: "¿Qué propiedad permite escalar, rotar o mover un elemento?", options: ["transition", "animation", "transform", "change"], correct: 2 },
    { q: "¿Qué valor de 'transform' se usa para girar un elemento?", options: ["scale()", "translate()", "rotate()", "skew()"], correct: 2 },
    { q: "¿Qué valor de 'transform' se usa para cambiar el tamaño de un elemento?", options: ["resize()", "scale()", "magnify()", "rotate()"], correct: 1 },
    { q: "¿Qué propiedad suaviza el cambio de un estilo a otro durante un tiempo?", options: ["animation", "transition", "duration", "timing"], correct: 1 },
    { q: "¿En qué propiedad se define el nombre de una animación de fotogramas clave?", options: ["animation-name", "animation-duration", "@keyframes", "animation-id"], correct: 0 },
    { q: "¿Qué regla se usa para definir los pasos de una animación?", options: ["@steps", "@keyframes", "@animate", "@frames"], correct: 1 },
    { q: "¿Qué propiedad define cuánto tiempo dura una transición?", options: ["transition-delay", "transition-time", "transition-duration", "transition-speed"], correct: 2 },
    { q: "¿Qué propiedad se usa para cambiar el estilo de las viñetas de una lista?", options: ["list-style-type", "bullets-style", "list-type", "marker-style"], correct: 0 },
    { q: "¿Qué valor de 'list-style-type' quita las viñetas de una lista?", options: ["no-style", "none", "hidden", "zero"], correct: 1 },
    { q: "¿Qué propiedad permite que una imagen de fondo cubra todo el contenedor?", options: ["background-size: cover", "background-size: contain", "background-fit: all", "background-fill"], correct: 0 },
    { q: "¿Qué selector selecciona el elemento inmediatamente después de otro?", options: ["E F", "E > F", "E + F", "E ~ F"], correct: 2 },
    { q: "¿Qué propiedad controla la visibilidad pero mantiene el espacio del elemento?", options: ["display: none", "opacity: 0", "visibility: hidden", "filter: blur()"], correct: 2 },
    { q: "¿Qué unidad de medida equivale al 1% del ancho de la ventana?", options: ["vh", "vw", "vmin", "%"], correct: 1 },
    { q: "¿Qué unidad de medida equivale al 1% del alto de la ventana?", options: ["vw", "vh", "rem", "em"], correct: 1 },
    { q: "¿Qué propiedad permite que un elemento se comporte como una tabla?", options: ["display: table", "display: grid", "display: flex", "display: block"], correct: 0 },
    { q: "¿Qué propiedad se usa para separar los bordes de las celdas de una tabla?", options: ["border-spacing", "border-collapse", "cell-spacing", "padding"], correct: 0 },
    { q: "¿Qué valor de 'border-collapse' une los bordes de una tabla en uno solo?", options: ["join", "collapse", "separate", "single"], correct: 1 },
    { q: "¿Qué propiedad define si el texto puede romperse al final de una línea?", options: ["text-break", "word-wrap", "white-space", "line-break"], correct: 1 },
    { q: "¿Qué propiedad se usa para definir columnas en un diseño de texto?", options: ["column-count", "text-columns", "display: grid", "flex-direction"], correct: 0 },
    { q: "¿Qué propiedad define la URL de una imagen de fondo?", options: ["background-src", "background-image", "background-url", "background-link"], correct: 1 },
    { q: "¿Cómo se llama el área entre el contenido y el borde?", options: ["Margin", "Padding", "Outline", "Box"], correct: 1 },
    { q: "¿Cómo se llama el área más externa del modelo de caja?", options: ["Padding", "Border", "Margin", "Content"], correct: 2 },
    { q: "¿Qué propiedad permite cambiar la transparencia de un color sin afectar al texto?", options: ["opacity", "rgba()", "filter", "transparent"], correct: 1 },
    { q: "¿Qué propiedad añade un contorno por fuera del borde (sin ocupar espacio)?", options: ["border-outer", "outline", "box-shadow", "margin"], correct: 1 },
    { q: "¿Qué propiedad permite redimensionar un elemento manualmente (en navegadores)?", options: ["resize", "scale", "width", "overflow"], correct: 0 },
    { q: "¿Qué selector selecciona elementos que tienen un atributo específico?", options: ["div.clase", "div#id", "div[atributo]", "div:hover"], correct: 2 },
    { q: "¿Qué propiedad permite controlar el espaciado entre palabras?", options: ["letter-spacing", "word-spacing", "text-gap", "word-padding"], correct: 1 },
    { q: "¿Qué valor de 'position' se comporta como 'relative' hasta que llega a un punto del scroll?", options: ["absolute", "fixed", "sticky", "static"], correct: 2 },

    // KAHOOT
    { q: "Completa: h1 + p selecciona...", options: ["Primer párrafo", "Todos los párrafos", "Cualquier p", "Nietos p"], correct: 0 }
   
];