var database = database || {};

database.js = [
    { q: "¿Cuál es la mejor opción para incluir JS en un proyecto según el temario?", options: ["En el <head>", "Al final del <body>", "En un archivo aparte .js", "Dentro de la etiqueta <a>"], correct: 2 },
    { q: "¿Qué método se usa para escribir directamente en el documento HTML?", options: ["window.print()", "console.log()", "document.write()", "document.set()"], correct: 2 },
    { q: "¿Cómo se escribe un comentario de varias líneas en JavaScript?", options: ["// comentario", "/* comentario */", "", "## comentario"], correct: 1 },
    { q: "¿Qué palabra clave permite declarar una variable con ámbito de bloque?", options: ["var", "let", "block", "static"], correct: 1 },
    { q: "¿Cuál es el operador para comparar si dos valores son iguales en tipo y valor?", options: ["==", "=", "===", "!="], correct: 2 },
    { q: "¿Qué hace el operador '%'?", options: ["Calcula el porcentaje", "Divide dos números", "Devuelve el resto de la división", "Multiplica"], correct: 2 },
    { q: "¿Cómo se define una función en JavaScript?", options: ["function:myFunc()", "function myFunction()", "def myFunction()", "void myFunction()"], correct: 1 },
    { q: "¿Qué objeto representa al navegador?", options: ["document", "navigator", "window", "browser"], correct: 2 },
    { q: "¿Qué método selecciona un elemento por su ID?", options: ["getElementByClass", "querySelector", "getElementById", "getId"], correct: 2 },
    { q: "¿Qué propiedad cambia el contenido HTML de un elemento?", options: ["textContent", "innerHTML", "value", "content"], correct: 1 },
    { q: "¿Cómo se accede al valor de un campo de texto de un formulario?", options: [".content", ".text", ".value", ".val()"], correct: 2 },
    { q: "¿Qué método añade un nodo como último hijo de un elemento?", options: ["insertChild()", "appendChild()", "addNode()", "setNode()"], correct: 1 },
    { q: "¿Para qué sirve el método console.log()?", options: ["Mostrar alertas", "Imprimir la página", "Depuración en la consola", "Guardar datos"], correct: 2 },
    { q: "¿Qué significa 'Serializar' un objeto?", options: ["Borrar el objeto", "Transformarlo en una cadena de texto", "Duplicar el objeto", "Ocultarlo"], correct: 1 },
    { q: "¿Cuál es el formato estándar para intercambio de datos en la web?", options: ["XML", "CSV", "JSON", "TXT"], correct: 2 },
    { q: "¿Qué método transforma un objeto JS en una cadena JSON?", options: ["JSON.parse()", "JSON.toString()", "JSON.stringify()", "JSON.serialize()"], correct: 2 },
    { q: "¿Qué método transforma una cadena JSON en un objeto JS?", options: ["JSON.parse()", "JSON.stringify()", "JSON.toObject()", "JSON.convert()"], correct: 0 },
    { q: "¿Qué significan las siglas AJAX?", options: ["Advanced JS and XML", "Asynchronous JS and XML", "Automatic JS and XHTML", "All JS and XML"], correct: 1 },
    { q: "¿Qué función de JS se usa actualmente para hacer peticiones HTTP?", options: ["getHTTP()", "xmlRequest()", "fetch()", "httpRequest()"], correct: 2 },
    { q: "¿Qué permite hacer el método 'then()' en una promesa?", options: ["Detener la ejecución", "Manejar la respuesta cuando llega", "Enviar datos", "Borrar la petición"], correct: 1 },
    { q: "¿Para qué sirve 'encodeURIComponent()'?", options: ["Encriptar contraseñas", "Codificar caracteres especiales en una URL", "Comprimir archivos", "Traducir código"], correct: 1 },
    { q: "¿Qué hace 'URLSearchParams'?", options: ["Busca virus", "Crea automáticamente parámetros de URL", "Borra el historial", "Cambia el dominio"], correct: 1 },
    { q: "¿Qué cabecera indica que enviamos datos en formato JSON?", options: ["Content-Type: application/json", "Type: text/json", "Format: json", "Accept: json"], correct: 0 },
    { q: "¿Qué método de envío de datos es más seguro para información sensible?", options: ["GET", "PUT", "POST", "DELETE"], correct: 2 },
    { q: "¿Qué estructura se usa para manejar errores en código asíncrono?", options: ["if/else", "switch/case", "try/catch", "for/in"], correct: 2 },
    { q: "¿Qué hace el método 'document.createElement()'?", options: ["Borra un elemento", "Crea un nuevo nodo de elemento", "Modifica un estilo", "Crea una variable"], correct: 1 },
    { q: "¿Cómo se quita el foco de un elemento?", options: ["onfocus", "onblur", "onclick", "onchange"], correct: 1 },
    { q: "¿Qué símbolo inicia una Expresión Regular en JS?", options: ["#", "@", "/", "$"], correct: 2 },
    { q: "¿Para qué sirve el método '.test()' en una expresión regular?", options: ["Crear un examen", "Verificar si una cadena cumple el patrón", "Borrar texto", "Unir dos cadenas"], correct: 1 },
    { q: "¿Qué objeto se usa para crear una fecha en JS?", options: ["Time()", "Clock()", "Date()", "Calendar()"], correct: 2 },
    { q: "¿JavaScript es un lenguaje de programación...?", options: ["Compilado", "Interpretado", "Solo para bases de datos", "De bajo nivel"], correct: 1 },
    { q: "¿Cómo se define una constante en JS?", options: ["var", "let", "const", "fixed"], correct: 2 },
    { q: "¿Qué valor devuelve 'typeof 42'?", options: ["string", "integer", "number", "float"], correct: 2 },
    { q: "¿Cuál es el resultado de '5' + 2 en JavaScript?", options: ["7", "52", "NaN", "Error"], correct: 1 },
    { q: "¿Cómo se llama a una función llamada 'miFuncion'?", options: ["call miFuncion()", "miFuncion()", "execute miFuncion()", "run miFuncion"], correct: 1 },
    { q: "¿Qué estructura se usa para ejecutar código si una condición es falsa?", options: ["if", "else", "switch", "while"], correct: 1 },
    { q: "¿Cuál es el operador lógico 'Y' (AND)?", options: ["||", "&", "&&", "!"], correct: 2 },
    { q: "¿Cuál es el operador lógico 'O' (OR)?", options: ["||", "&&", "OR", "|"], correct: 0 },
    { q: "¿Cómo se inicia un bucle 'for' correctamente?", options: ["for (i <= 5; i++)", "for (let i = 0; i < 5; i++)", "for i = 1 to 5", "for (let i = 0; i < 5)"], correct: 1 },
    { q: "¿Qué bucle garantiza que el código se ejecute al menos una vez?", options: ["for", "while", "do...while", "foreach"], correct: 2 },

    // ARRAYS Y OBJETOS
    { q: "¿Cómo se declara un array vacío?", options: ["let a = {}", "let a = []", "let a = array()", "let a = new Array()"], correct: 1 },
    { q: "¿Qué propiedad devuelve el número de elementos de un array?", options: ["count", "size", "length", "index"], correct: 2 },
    { q: "¿Qué método añade un elemento al FINAL de un array?", options: ["pop()", "shift()", "push()", "unshift()"], correct: 2 },
    { q: "¿Qué método elimina el ÚLTIMO elemento de un array?", options: ["pop()", "push()", "remove()", "delete()"], correct: 0 },
    { q: "¿Qué método elimina el PRIMER elemento de un array?", options: ["pop()", "shift()", "push()", "unshift()"], correct: 1 },
    { q: "¿Qué método añade un elemento al PRINCIPIO de un array?", options: ["push()", "unshift()", "shift()", "addFirst()"], correct: 1 },
    { q: "¿Cómo se accede al primer elemento de un array llamado 'datos'?", options: ["datos[1]", "datos[0]", "datos.first()", "datos{0}"], correct: 1 },
    { q: "¿Cómo se define un objeto con las propiedades nombre y edad?", options: ["{nombre: 'Ana', edad: 25}", "['Ana', 25]", "nombre='Ana', edad=25", "object(nombre, edad)"], correct: 0 },
    { q: "¿Cómo se accede a la propiedad 'nombre' de un objeto 'persona'?", options: ["persona['nombre']", "persona.nombre", "Ambas son correctas", "persona->nombre"], correct: 2 },
    { q: "¿Qué hace el método 'splice()' en un array?", options: ["Corta el array", "Añade o elimina elementos en cualquier posición", "Invierte el array", "Une dos arrays"], correct: 1 },

    // DOM Y EVENTOS
    { q: "¿Qué objeto representa la página web cargada?", options: ["window", "document", "screen", "location"], correct: 1 },
    { q: "¿Qué método selecciona TODOS los elementos que coinciden con un selector CSS?", options: ["getElementById", "getElementsByClassName", "querySelectorAll", "querySelector"], correct: 2 },
    { q: "¿Qué propiedad se usa para cambiar el estilo CSS de un elemento?", options: ["element.css", "element.style", "element.class", "element.design"], correct: 1 },
    { q: "¿Cómo se cambia el color de texto a rojo con JS?", options: ["style.color = 'red'", "color('red')", "text-color: red", "style.font = 'red'"], correct: 0 },
    { q: "¿Qué evento ocurre cuando el usuario hace clic en un elemento?", options: ["onmouseover", "onchange", "onclick", "onsubmit"], correct: 2 },
    { q: "¿Qué evento se dispara al terminar de cargar la página?", options: ["onload", "onready", "onfinish", "onstart"], correct: 0 },
    { q: "¿Qué evento detecta que se ha cambiado el valor de un input o select?", options: ["onclick", "onchange", "onfocus", "onblur"], correct: 1 },
    { q: "¿Para qué sirve 'event.preventDefault()'?", options: ["Detiene la propagación", "Cancela la acción por defecto (ej. envío de form)", "Borra el evento", "Muestra un error"], correct: 1 },
    { q: "¿Qué método permite escuchar un evento sin usar atributos HTML?", options: ["setEvent()", "addEventListener()", "listen()", "attach()"], correct: 1 },
    { q: "¿Qué propiedad devuelve el nodo padre de un elemento?", options: ["childNode", "parentNode", "mainNode", "superNode"], correct: 1 },

    // BROWSER OBJECT MODEL (BOM)
    { q: "¿Qué método muestra un cuadro de diálogo con un mensaje y botón OK?", options: ["confirm()", "prompt()", "alert()", "print()"], correct: 2 },
    { q: "¿Qué método pide al usuario que introduzca un texto?", options: ["alert()", "confirm()", "prompt()", "input()"], correct: 2 },
    { q: "¿Qué método devuelve true o false tras una pregunta al usuario?", options: ["alert()", "confirm()", "prompt()", "check()"], correct: 1 },
    { q: "¿Qué propiedad de 'window.location' devuelve la URL actual?", options: ["hostname", "pathname", "href", "protocol"], correct: 2 },
    { q: "¿Qué objeto del BOM permite retroceder en el historial?", options: ["window.back", "window.history", "window.screen", "window.navigator"], correct: 1 },
    { q: "¿Qué método del historial carga la página anterior?", options: ["history.next()", "history.back()", "history.go(-1)", "Las opciones 2 y 3 son correctas"], correct: 3 },
    { q: "¿Qué propiedad indica si las cookies están habilitadas?", options: ["navigator.cookieEnabled", "window.cookies", "document.cookie", "navigator.javaEnabled"], correct: 0 },
    { q: "¿Para qué sirve 'window.open()'?", options: ["Cerrar el navegador", "Abrir una nueva ventana o pestaña", "Abrir la consola", "Imprimir"], correct: 1 },
    { q: "¿Qué objeto da información sobre la resolución de la pantalla?", options: ["window.display", "window.screen", "window.monitor", "window.view"], correct: 1 },
    { q: "¿Cómo se detiene un intervalo creado con 'setInterval'?", options: ["stopInterval()", "endInterval()", "clearInterval()", "breakInterval()"], correct: 2 },

    // AJAX Y ASINCRONÍA
    { q: "¿Qué significa que AJAX es asíncrono?", options: ["Bloquea la página hasta que termina", "No bloquea la página mientras espera la respuesta", "Solo funciona con archivos XML", "Se ejecuta solo al cargar la página"], correct: 1 },
    { q: "¿Qué propiedad de XMLHttpRequest contiene el estado de la petición?", options: ["status", "readyState", "state", "response"], correct: 1 },
    { q: "¿Qué valor de 'readyState' indica que la petición ha finalizado?", options: ["1", "2", "3", "4"], correct: 3 },
    { q: "¿Qué código de estado HTTP indica que la petición fue exitosa?", options: ["404", "500", "200", "302"], correct: 2 },
    { q: "¿Qué código de estado HTTP indica que el recurso no se encontró?", options: ["200", "404", "403", "500"], correct: 1 },
    { q: "¿Para qué sirve el método 'open()' en XMLHttpRequest?", options: ["Envía los datos", "Configura el método, la URL y si es asíncrono", "Recibe la respuesta", "Abre un archivo local"], correct: 1 },
    { q: "¿Qué método de XMLHttpRequest envía finalmente la petición al servidor?", options: ["execute()", "send()", "post()", "start()"], correct: 1 },
    { q: "¿Cómo se maneja un error en una promesa 'fetch'?", options: [".error()", ".catch()", ".finally()", ".stop()"], correct: 1 },
    { q: "¿Qué devuelve la función 'fetch()'?", options: ["Un objeto JSON", "Una cadena de texto", "Una Promesa", "Un array"], correct: 2 },
    { q: "¿Qué hace el método '.json()' aplicado a la respuesta de fetch?", options: ["Convierte la respuesta en un objeto JS", "Borra el JSON", "Envía un JSON", "Valida el JSON"], correct: 0 },

    // EXPRESIONES REGULARES Y VARIOS
    { q: "¿Qué modificador en una RegExp hace que no distinga entre mayúsculas y minúsculas?", options: ["g", "m", "i", "s"], correct: 2 },
    { q: "¿Qué modificador en una RegExp realiza una búsqueda global?", options: ["i", "g", "all", "x"], correct: 1 },
    { q: "¿Qué carácter representa 'cualquier dígito' en una RegExp?", options: ["\\w", "\\d", "\\s", "\\t"], correct: 1 },
    { q: "¿Qué carácter representa el inicio de una cadena en una RegExp?", options: ["^", "$", "*", "+"], correct: 0 },
    { q: "¿Qué carácter representa el final de una cadena en una RegExp?", options: ["^", "$", ".", "?"], correct: 1 },
    { q: "¿Qué hace el método 'match()' de los Strings?", options: ["Busca una coincidencia usando RegExp", "Reemplaza texto", "Divide un string", "Une dos strings"], correct: 0 },
    { q: "¿Cómo se escapa un carácter especial en una RegExp?", options: ["/", "//", "\\", "!"], correct: 2 },
    { q: "¿Qué significa el cuantificador '+' en una RegExp?", options: ["Cero o más veces", "Exactamente una vez", "Una o más veces", "Opcional"], correct: 2 },
    { q: "¿Qué significa el cuantificador '*' en una RegExp?", options: ["Cero o más veces", "Una o más veces", "Exactamente una vez", "Ninguna vez"], correct: 0 },

    // KAHOOT
    { q: "¿Qué es un jQuery?", options: ["Un motor de plantillas", "Un framework de CSS", "Un lenguaje de servidor", "Una biblioteca de JavaScript"], correct: 3 },
    { q: "¿Qué vulnerabilidad en JS implica la insercción y ejecución de código malicioso?", options: ["XSS (Cross-Site Scripting)", "Inyección de SQL", "Tabnabbing", "Fuga de información"], correct: 0 },
    { q: "¿Qué tecnología de Java, que permite incrustar código Java en HTML, ha sido sustituido por frameworks como Spring", options: ["JSP (Java Server Pages)", "Servlets", "JPA (Java Persistence API)", "JDBC (Java Database Connectivity)"], correct: 0 },
    { q: "¿Cuál es el tipo devuelto por JSON.parse()?", options: ["string", "number", "object", "boolean"], correct: 2 },
    { q: "¿Cuál método evita recargar la página?", options: ["blockReload()", "event.preventDefault()", "haltDefault()", "stopPropagation()"], correct: 1 },
    { q: "¿Qué objeto empaqueta formulario automáticamente?", options: ["FormData", "Headers", "Request", "URLSearchParams"], correct: 0 },
    { q: "¿Cómo capturas errores con Fetch moderno?", options: ["try/catch await", ".if/error", "switch/case", "throwOnly"], correct: 0 },
    { q: "¿Qué devuelve typeof tras JSON.stringify?", options: ["object", "string", "array", "json"], correct: 1 },
    { q: "¿Qué diferencia a textContent?", options: ["Ignora HTML", "Oculta espacios", "Ejecuta scripts", "Incluye etiquetas"], correct: 0 },
    { q: "¿Qué método crea nodos rápidos off-DOM?", options: ["createTextNode()", "appendChild()", "cloneNode()", "createDocumentFragment()"], correct: 3 },
    { q: "¿Qué retorna querySelectrorAll?", options: ["Set", "NodeList", "Array", "HTMLCollection"], correct: 1 },
    { q: "¿Cuál es el peligro de innerHTML?", options: ["Rompe DOM", "XSS posible", "Quita estilos", "Lento siempre"], correct: 1 },
    { q: "¿Qué evento indica DOM listo?", options: ["load", "DOMContentLoaded", "beforeprint", "ready"], correct: 1 },
    { q: "Completa: let tiene ámbito...", options: ["GGlobal", "De función", "De bloque", "Privado"], correct: 2 },  
    { q: "¿Qué método registra eventos estándar?", options: ["addEventListener()", "attachEvent()", "onClick()", "listen()" ], correct: 0 },
    { q: "¿Qué propiedad escribe HTML con etiquetas?", options: ["textContent", "innerText", "innerHTML", "outerText"], correct: 2 }
   
    
];