var database = database || {};

database.tema3 = [
    // 01. TIPOS DE INFORMACIÓN
    { q: "¿Cuáles son los tres grandes bloques de tipos de información que se definen en el tema?", options: ["Archivos, Registros y Metadatos", "Datos desestructurados, Datos semi-estructurados y Datos estructurados", "MySQL, JSON y Crawlers", "Front-end, Back-end y APIs"], correct: 1 },
    { q: "¿Cómo se caracterizan los datos desestructurados según los apuntes?", options: ["Registros con estructura fija y fuertemente tipada", "Colecciones no ordenadas de pares clave-valor", "Archivos de texto, vídeo, audio, imágenes, presentaciones... difíciles de tratar y almacenar en BD", "Documentos con marcado XML Schema estructurado"], correct: 2 },
    { q: "¿Cuál de los siguientes es un ejemplo explícito de datos semi-estructurados en el tema?", options: ["Una base de datos de Oracle", "Un Curriculum Vitae (con cierta estructura, pero no muy rígida)", "Un archivo de vídeo en MP4", "Una tabla fuertemente tipada"], correct: 1 },
    { q: "Los datos que presentan todos sus registros con una estructura fija y fuertemente tipada se denominan:", options: ["Datos no estructurados", "Datos semi-estructurados", "Datos estructurados", "Ontologías complejas"], correct: 2 },

    // 02. GESTIÓN DE DATOS ESTRUCTURADOS (Modelo Relacional y Privilegios)
    { q: "¿Qué sistemas usualmente implementan la mayoría de las funcionalidades necesarias para gestionar datos estructurados?", options: ["Sistemas NoSQL basados en clave-valor", "Sistemas de Gestión de Bases de Datos Relacionales (SGBDR)", "Spiders o indexadores automatizados", "Librerías de mapeado JSON"], correct: 1 },
    { q: "¿Cuáles son los cuatro ejemplos de SGBDR que se listan textualmente en las diapositivas?", options: ["MongoDB, Cassandra, BigTable y Redis", "MySQL, PostgreSQL, SQLite y Oracle", "JSON, XML, CSV y MathML", "Laravel, Spring, Apache y NGINX"], correct: 1 },
    { q: "Dentro de la seguridad en el diseño de BBDD, ¿quién debe tener privilegios para todo de forma exclusiva?", options: ["Las aplicaciones web de usuario", "El administrador de red local", "Solo el propietario", "Cualquier usuario autenticado"], correct: 2 },
    { q: "¿Qué práctica de seguridad NO se debe permitir nunca en las aplicaciones según el tema?", options: ["Conectarse utilizando conexiones persistentes", "Conectarse a la base de datos como superusuario", "Crear un usuario diferente con privilegios limitados", "Utilizar la API mysqli o la clase PDO"], correct: 1 },
    { q: "Para que otros usuarios utilicen la base de datos de manera segura, se recomienda:", options: ["Compartir la contraseña del superusuario", "Crear un usuario diferente, concediendo privilegios limitados", "Deshabilitar el motor relacional de almacenamiento", "Pasar los datos relacionales a un archivo plano CSV"], correct: 1 },

    // 02. GESTIÓN DE DATOS ESTRUCTURADOS (Inyección de código)
    { q: "¿Qué popular cómic o imagen se cita en el tema para ilustrar una inyección de código SQL?", options: ["Una tira cómica de Dilbert", "Una imagen de xkcd (Little Bobby Tables)", "Un meme de programación de Reddit", "Una captura de pantalla de StackOverflow"], correct: 1 },
    { q: "Definición formal de inyección de código/SQL según el tema:", options: ["Técnica donde se duplican las tablas para saturar el disco del servidor", "Técnica de ataque en la que un atacante inserta o 'inyecta' código SQL malicioso en una consulta a través de la entrada de un usuario", "Un fallo que ocurre al no cerrar conexiones persistentes en PHP", "Convertir un objeto de JavaScript en una cadena JSON mal formateada"], correct: 1 },
    { q: "¿Cuáles son las tres consecuencias o peligros directos enumerados de la inyección SQL?", options: ["Saturación de RAM, caída de DNS y pérdida de dominio", "Acceso no autorizado, modificación/eliminación de datos y ejecución de comandos en el servidor", "Vendor lock-in, aumento de OPEX y deuda técnica", "Scraping masivo, bloqueo de IPs y captchas"], correct: 1 },
    { q: "¿Qué sucede en una Inyección SQL In-Band?", options: ["El atacante no ve los resultados directamente, sino por respuestas booleanas", "El atacante induce errores en la base de datos para obtener información", "El atacante obtiene los resultados de la consulta maliciosa en el mismo canal que se utiliza para explotarla", "El ataque se realiza exclusivamente sobre archivos PDF e imágenes"], correct: 2 },
    { q: "¿Qué técnica induce fallos de forma voluntaria para extraer información de la base de datos?", options: ["Inyección SQL a Ciegas", "Inyección SQL Basada en Errores", "Inyección SQL In-Band", "Sanitización mediante filter_var"], correct: 1 },
    { q: "¿Cómo infiere información un atacante en una Inyección SQL a Ciegas?", options: ["A través del canal de depuración de la consola web", "Viendo los volcados completos de tablas en la pantalla", "A través de respuestas booleanas (verdadero/falso)", "Mediante el uso de un mapa del sitio (Sitemap)"], correct: 2 },
    { q: "En un ejemplo de inyección en autenticación, ¿qué caracteres se añaden como entrada maliciosa para anular la contraseña del script?", options: ["admin' --", "DROP TABLE users;", "1 OR 1=1", "%'; CLEAR;"], correct: 0 },
    { q: "En una consulta 'SELECT * FROM products WHERE name LIKE '%$search%'', ¿qué entrada maliciosa se muestra para borrar la tabla?", options: ["admin' --", "1 OR 1=1", "%'; DROP TABLE products; --", "AND 1=2"], correct: 2 },
    { q: "En una inyección basada en errores, ¿qué entrada maliciosa típica fuerza que la condición del WHERE sea siempre verdadera?", options: ["admin' --", "1 OR 1=1", "1 AND 1=2", "id=null"], correct: 1 },
    { q: "En una inyección a ciegas sobre 'WHERE id = $id', ¿qué comparaciones booleanas se prueban como entrada maliciosa?", options: ["admin' -- y %'--", "1 OR 1=1 y 1 OR 2=2", "1 AND 1=1 (verdadero) o 1 AND 1=2 (falso)", "DROP DATABASE TABLICE"], correct: 2 },

    // 02. GESTIÓN DE DATOS ESTRUCTURADOS (Soluciones a la Inyección)
    { q: "¿Qué diferencia hay entre Validación y Sanitización según el texto?", options: ["La validación limpia los datos y la sanitización duplica las variables", "La validación verifica que los datos cumplan ciertos criterios (ej. formato); la sanitización limpia los datos eliminando caracteres peligrosos", "Son términos idénticos en PHP que invocan a PDO de forma nativa", "La validación opera en la capa de transporte y la sanitización en la de aplicación"], correct: 1 },
    { q: "¿Qué función nativa de PHP se utiliza en los apuntes como ejemplo para validar un correo electrónico?", options: ["filter_var($email, FILTER_VALIDATE_EMAIL)", "filter_var($nombre, FILTER_SANITIZE_STRING)", "htmlspecialchars($codigo)", "mysqli_query($conn, $query)"], correct: 0 },
    { q: "¿Qué ejemplo de código se da para sanitizar una cadena de texto en PHP?", options: ["filter_var($email, FILTER_VALIDATE_EMAIL)", "filter_var($nombre, FILTER_SANITIZE_STRING)", "bind_param('ss', $username)", "eval($codigo)"], correct: 1 },
    { q: "¿En qué consiste el uso de Declaraciones Preparadas y Consultas Parametrizadas?", options: ["En encriptar los datos antes de guardarlos en el disco duro", "En separar la lógica SQL de los datos", "En deshabilitar la base de datos relacional", "En limpiar manualmente usando expresiones regulares"], correct: 1 },
    { q: "¿Qué método de un objeto de sentencia (stmt) se encarga de vincular las variables seguras en PHP?", options: ["prepare()", "execute()", "bind_param()", "mysqli_query()"], correct: 2 },
    { q: "¿Qué cadena de tipado se le pasa a bind_param() en el ejemplo para enlazar dos strings ($username, $password)?", options: ["'ss'", "'ii'", "'string'", "'&&'"], correct: 0 },
    { q: "¿Qué funciones peligrosas que ejecutan código arbitrario se deben evitar según el tema?", options: ["prepare() y execute()", "eval(), exec(), system() y passthru()", "json_encode() y json_decode()", "filter_var() y htmlspecialchars()"], correct: 1 },
    { q: "¿Cuál es la alternativa segura propuesta en PHP para evitar los riesgos de usar eval($codigo)?", options: ["mysqli_query($conn, $codigo)", "htmlspecialchars($codigo, ENT_QUOTES, 'UTF-8')", "filter_var($codigo, FILTER_VALIDATE_EMAIL)", "bind_param($codigo)"], correct: 1 },
    { q: "Dentro de la configuración segura de PHP, ¿qué directiva permite deshabilitar funciones que afectan al Sistema Operativo?", options: ["mysqli.max_persistent", "disable_functions", "noNamespaceSchemaLocation", "PDO::ATTR_PERSISTENT"], correct: 1 },
    { q: "¿Qué funciones específicas se sugiere poner dentro de la directiva 'disable_functions'?", options: ["json_encode, json_decode", "exec, system, passthru, shell_exec, proc_open, popen", "mysqli_query, PDO", "filter_var, htmlspecialchars"], correct: 1 },
    { q: "¿Qué framework moderno se cita como ejemplo de herramienta que ya incorpora buenas prácticas de seguridad y protege contra SQL injection y XSS?", options: ["Spring Boot", "Django", "Laravel", "Angular"], correct: 2 },
    { q: "¿En qué consiste la solución de 'Monitoreo y Auditoría' ante inyecciones de código?", options: ["Lanzar captchas de forma masiva a todos los usuarios", "Vigilar, registrar y revisar lo que ocurre en la aplicación y en el servidor para detectar fallos, abusos o intentos de ataque", "Deshabilitar las cookies de sesión", "Utilizar únicamente bases de datos NoSQL clave-valor"], correct: 1 },

    // 02. GESTIÓN DE DATOS ESTRUCTURADOS (Conexiones Persistentes)
    { q: "¿Qué es una conexión persistente según el tema?", options: ["Una conexión que se cifra con SSL/TLS en la capa de transporte", "Enlaces a una BD que no se cierran al finalizar la ejecución de un script", "Una conexión que requiere autenticación por certificado electrónico", "Un enlace a una BD NoSQL orientada a grafos"], correct: 1 },
    { q: "Al solicitar una conexión persistente, ¿qué hace PHP internamente?", options: ["Abre una máquina virtual nueva en la nube", "Comprueba si ya hay una conexión idéntica abierta y la reutiliza", "Lanza una alerta de advertencia (warning) automática", "Ejecuta un rollback de todas las tablas"], correct: 1 },
    { q: "¿Cuáles son las dos ventajas principales de las conexiones persistentes?", options: ["Mayor seguridad contra XSS y eliminación de la deuda técnica", "Reducción de la latencia (evita tiempo de establecimiento) y eficiencia en el uso de recursos (menor carga)", "Limpieza automática de memoria Front-end y parseo inmediato", "Compatibilidad total con robots.txt y sitemaps"], correct: 1 },
    { q: "¿Cuáles son los inconvenientes de usar conexiones persistentes?", options: ["Hacen que el código ocupe más líneas y no validan correos", "Estados inesperados (bloqueos, transacciones abiertas) y consumo de recursos de forma innecesaria cuando no se usan", "Son incompatibles con el framework Laravel", "Fuerzan a que el servidor use obligatoriamente IPv6"], correct: 1 },
    { q: "Con el API mysqli, ¿cómo se indica que una conexión es de tipo persistente?", options: ["Añadiendo el parámetro 'persistent => true'", "Añadiendo el prefijo 'p:' al host (ej. 'p:localhost')", "Invocando al método mysqli_persistent()", "Pasando el parámetro PDO::ATTR_PERSISTENT"], correct: 1 },
    { q: "Con la clase PDO, ¿cómo se activa una conexión persistente?", options: ["Usando el prefijo 'p:' en el string del host", "Pasando 'PDO::ATTR_PERSISTENT => true' en el array de opciones", "Llamando a $pdo->setPersistent()", "La clase PDO las activa siempre por defecto"], correct: 1 },
    { q: "¿Cuál es la primera recomendación de uso para las conexiones persistentes?", options: ["Usarlas siempre en todos los scripts sin excepción", "Usarlas cuando haya necesidad de establecer acceso a la BD en numerosas ocasiones o por cuestiones de velocidad/seguridad", "Usarlas solo si la base de datos no es relacional", "Usarlas únicamente cuando se ejecute la función eval()"], correct: 1 },
    { q: "¿Qué importante recomendación de cierre se da sobre las conexiones?", options: ["No cerrarlas nunca para asegurar la persistencia infinita", "Cerrar la conexión cuando no sea necesario su uso", "Dejar que el archivo robots.txt las cierre remotamente", "Cerrarlas únicamente si devuelven un error HTTP 500"], correct: 1 },
    { q: "En las soluciones de PHP, ¿qué acciones realiza MySQLi de forma automática para limpiar una conexión persistente?", options: ["Borrar todas las contraseñas de los usuarios", "Rollback de transacciones activas, cierre de tablas temporales y desbloqueo de tablas", "Validar sintácticamente los archivos JSON", "Enviar una notificación al Contacto Técnico del dominio"], correct: 1 },
    { q: "¿Qué parámetros de configuración permiten limitar el número de conexiones persistentes en PHP?", options: ["disable_functions", "mysqli.max_persistent y mysqli.max_links", "xmlns:xsi y xsi:noNamespaceSchemaLocation", "json_encode y json_decode"], correct: 1 },

    // 03. GESTIÓN DE DATOS SEMI-ESTRUCTURADOS (NoSQL y XML)
    { q: "Al comparar la gestión, ¿qué aclaran las diapositivas sobre los datos semi-estructurados?", options: ["Que es mucho más sencilla que la de los estructurados", "Que puede ser más compleja que los datos estructurados", "Que no se pueden almacenar en ningún tipo de SGBD", "Que son exclusivos de los navegadores de Microsoft"], correct: 1 },
    { q: "¿Qué dos formatos se listan como ejemplos principales de datos semi-estructurados?", options: ["SQL y Oracle", "JSON y XML", "PDF y MP4", "HTML estático y CSS"], correct: 1 },
    { q: "¿Qué siglas y tecnologías de SGBD se recomiendan para datos no/semi estructurados?", options: ["SGBDR (MySQL, SQLite)", "NoSQL (MongoDB de tipo JSON, Cassandra/BigTable de tipo Clave-Valor)", "ESB (Enterprise Service Bus heterogéneo)", "APIs REST basadas puramente en CSV"], correct: 1 },
    { q: "Definición de XML según el temario:", options: ["Un lenguaje de consultas relacionales parametrizadas", "Metalenguaje de marcas para definir lenguajes de marcas, simplificación de SGML", "Un subconjunto de la notación literal de JavaScript", "Un robot que navega por grafos en profundidad"], correct: 1 },
    { q: "¿Cuáles son los cuatro lenguajes derivados de XML citados en la diapositiva correspondiente?", options: ["MySQL, PostgreSQL, SQLite y Oracle", "XHTML, Google Site Map, NewsML (News Markup Language) y OOXML (Office Open XML)", "JSON, CSV, BSON y TXT", "Math, Line, Rect y Circle"], correct: 1 },
    { q: "¿Qué aclaración o crítica se añade entre paréntesis sobre OOXML?", options: ["¡Es el mejor estándar!", "¡Muy rápido!", "¡Muy criticado!", "¡Es obsoleto!"], correct: 2 },
    { q: "Sintácticamente, ¿cómo se forma un documento XML?", options: ["Como una tabla rígida de registros fijos", "Como una jerarquía de contenidos en forma de árbol (etiquetado, ilimitado y ordenado)", "Como una secuencia de pares clave-valor sin orden", "Como una cadena plana separada por saltos de línea \\n"], correct: 1 },
    { q: "Un 'Elemento' en XML se compone de:", options: ["Una clave numérica y un valor booleano", "Etiqueta de apertura, contenido textual y etiqueta de fin", "Únicamente atributos metidos en llaves", "Pares clave-valor sin etiquetas de cierre"], correct: 1 },
    { q: "¿Qué componente de XML puede aparecer como pares clave-valor dentro de la etiqueta de apertura?", options: ["Entidades", "Atributos", "Prólogos", "Sitemaps"], correct: 1 },
    { q: "Respecto al orden en XML, ¿cuál es la regla de oro sobre los atributos y el contenido?", options: ["Los atributos están ordenados, el contenido no", "Los atributos NO están ordenados, el contenido SÍ", "Ambos tienen que estar estrictamente ordenados de forma alfabética", "Ninguno presenta ningún tipo de orden jerárquico"], correct: 1 },
    { q: "¿Qué compone el 'Prólogo' de un archivo XML?", options: ["Las constantes asignadas a las entidades", "La versión de XML, codificación y localización de recursos externos", "Los elementos hoja del subárbol jerárquico", "Los estilos de transformación XSL-FO"], correct: 1 },
    { q: "¿Qué son las 'Entidades' en XML?", options: ["Las etiquetas de fin del documento", "Referencias a contenidos asignados a constantes (ej. &tema1;)", "Las reglas de validación del esquema XSD", "Los atributos complejos de una etiqueta"], correct: 1 },

    // 03. GESTIÓN DE DATOS SEMI-ESTRUCTURADOS (DTD y XML-Schema)
    { q: "¿Qué significan las siglas DTD?", options: ["Data Type Data", "Document Type Definition", "Digital Transformation Design", "Dynamic Tabular Document"], correct: 1 },
    { q: "¿Cómo define el tema conceptualmente a un DTD?", options: ["Un framework seguro como Laravel", "Un conjunto de reglas que define la estructura y los elementos permitidos en un documento XML", "Un formato ligero y compacto basado en JavaScript", "Un robot que extrae emails con expresiones regulares"], correct: 1 },
    { q: "¿Cuáles son las dos grandes desventajas del uso de DTD descritas en el tema?", options: ["Es muy lento y no se puede meter dentro del XML", "No usa la sintaxis XML y no usa tipos de datos específicos ni espacios de nombres", "Es exclusivo de Oracle y cuesta dinero", "Sufre de inyecciones SQL de tipo In-Band"], correct: 1 },
    { q: "En el ejemplo de DTD, ¿qué palabra clave indica que un elemento contiene datos de texto formateados por caracteres?", options: ["#PCDATA", "xs:string", "CDATA_SAFE", "VARCHAR"], correct: 0 },
    { q: "En la definición de elementos del DTD de un email, ¿qué significa el modificador 'cc?'?", options: ["Que el elemento cc debe aparecer exactamente dos veces", "Que el elemento cc es opcional (puede aparecer cero o una vez)", "Que es un elemento con herencia compleja", "Que es una restricción de cardinalidad estricta"], correct: 1 },
    { q: "En el DTD, ¿qué significa el modificador asterisco en '(paragraph*)'?", options: ["Que el elemento es obligatorio y no puede estar vacío", "Que puede aparecer cero o más veces", "Que es un atributo no ordenado", "Que contiene una fórmula matemática de MathML"], correct: 1 },
    { q: "¿Qué estándar moderno sustituye al DTD para definir las reglas y estructura de un XML?", options: ["SGML", "XML-Schema o XSD", "JSON.parse()", "Ontologías OWL"], correct: 1 },
    { q: "¿Qué entidad propuso el estándar XML-Schema (XSD)?", options: ["Google e ICANN", "El W3C", "El creador de Laravel", "xkcd corporativo"], correct: 1 },
    { q: "¿Qué comparación de complejidad hace el tema entre XML-Schema y DTD?", options: ["XML-Schema es mucho más simple que DTD", "XML-Schema es muy versátil pero bastante más complicado que los DTDs", "Son idénticos en sintaxis y complejidad", "XSD no permite definir atributos y DTD sí"], correct: 1 },
    { q: "En un XML-Schema, ¿qué etiqueta define que un elemento contiene subelementos o una secuencia ordenada?", options: ["<xs:simpleType>", "<xs:complexType>", "<xs:attribute>", "<xs:string>"], correct: 1 },
    { q: "¿Qué atributos de XML-Schema permiten definir que un elemento puede aparecer de forma ilimitada o ser opcional?", options: ["minOccurs y maxOccurs='unbounded'", "disable_functions y filter_var", "xmlns:xsi y sitemap_size", "p:localhost y attribute_true"], correct: 0 },

    // 03. GESTIÓN DE DATOS SEMI-ESTRUCTURADOS (Usos XML: Sitemaps, MathML, SVG, XSL)
    { q: "¿Qué es un SITEMAP técnico según el tema?", options: ["Un archivo plano CSV que guarda precios", "Un archivo XML que describe la estructura jerárquica de tu web (páginas, categorías, subpáginas) para mejorar la navegación e indexación", "Una directiva de metaetiqueta que impide que Google te rastree", "Un lenguaje para incrustar fórmulas en LaTeX"], correct: 1 },
    { q: "¿Qué herramienta online gratuita se cita explícitamente en una captura para generar mapas de sitios XML?", options: ["Blogger.com", "XML-Sitemaps.com", "Kahoot.it", "Google Analytics"], correct: 1 },
    { q: "En el ejemplo real analizado en la herramienta XML-Sitemaps, ¿la web personal de qué profesor de la UGR se escanea?", options: ["Sergio Alonso Burgos", "Carmen Martínez Cruz", "Rafael Payá Albert", "Daniel Vega Jiménez"], correct: 2 },
    { q: "¿Para qué sirve el lenguaje MathML?", options: ["Para diseñar gráficos vectoriales interactivos", "Para describir fórmulas matemáticas mediante XML", "Para transformar JSON a colecciones de objetos", "Para auditar la seguridad de las bases de datos"], correct: 1 },
    { q: "¿Qué siglas corresponden al formato basado en XML para describir gráficos vectoriales escalables?", options: ["CSV", "SVG", "MathML", "XSD"], correct: 1 },
    { q: "En el código SVG de ejemplo, ¿qué etiquetas nativas se usan para dibujar figuras geométricas?", options: ["<math> y <apply>", "<rect> (con atributos de posición, tamaño y estilo)", "<xs:element>", "<catalog> y <book>"], correct: 1 },
    { q: "¿Qué significa XSL y para qué sirve principalmente?", options: ["Xml System Language; sirve para enrutar paquetes IP", "Extensible Stylesheet Language; sirve para darle estilo a los documentos XML", "X-Site Location; sirve para evitar ataques de inyección", "X-Sub-Level; para definir herencia relacional"], correct: 1 },
    { q: "¿Cuáles son los tres componentes que integran la tecnología XSL?", options: ["HTML, CSS y JavaScript", "XSLT (transformación), Xpath (navegación) y XSL-FO (formateo)", "JSON, BSON y XML-Schema", "MySQLi, PDO y bind_param"], correct: 1 },

    // 03. GESTIÓN DE DATOS SEMI-ESTRUCTURADOS (JSON)
    { q: "Definición formal de JSON según los apuntes:", options: ["Un metalenguaje derivado de SGML para noticias empresariales", "Formato de texto sencillo para el intercambio de información (subconjunto de la notación literal de objetos de JavaScript)", "Una base de datos orientada a grafos jerárquicos", "Una técnica ilegal de extracción masiva de datos"], correct: 1 },
    { q: "¿Cuáles son los tipos de datos disponibles en la sintaxis de JSON listados en el tema?", options: ["Integer, Float, Varchar, Blob y Date", "Números, Cadenas (con doble comilla), Booleanos (true/false), Valor nulo (null), Array (entre corchetes) y Objetos (entre llaves)", "Elementos, Atributos, Prólogos, Entidades y DTDs", "Clases, Instancias, Relaciones, Herencia y Restricciones"], correct: 1 },
    { q: "En un objeto JSON, las colecciones de pares nombre-valor deben cumplir que el nombre sea:", options: ["Un número entero único", "Una cadena entre comillas dobles", "Una etiqueta con cierre obligatorio", "Una variable con el prefijo '$'"], correct: 1 },
    { q: "Mencione tres ventajas críticas de JSON enumeradas en el tema:", options: ["Usa sintaxis XML, es pesado y soporta software legado", "Fácil de entender para humanos, menos pesado que XML, amplio soporte en APIs REST e integración sencilla con JS", "Permite inyecciones a ciegas, automatiza el enrutamiento IP y no consume RAM", "Funciona sin conexión a internet y limpia bases de datos relacionales"], correct: 1 },
    { q: "Según la tabla comparativa entre JSON y XML, ¿cuál es el formato más rápido y ligero?", options: ["XML es más rápido y ligero", "JSON es más ligero, con sintaxis simple y más rápido; ideal para APIs", "Ambos pesan exactamente lo mismo al traducirse a binario", "XML es mejor para APIs modernas y JSON para documentos antiguos"], correct: 1 },
    { q: "¿Qué funciones usuales de PHP se listan en una tabla para trabajar con JSON?", options: ["mysqli_query() y PDO::prepare()", "json_encode(), json_decode(), json_last_error() y json_last_error_msg()", "JSON.stringify() y JSON.parse()", "filter_var() y htmlspecialchars()"], correct: 1 },
    { q: "En PHP, ¿para qué sirve el parámetro u opción 'JSON_UNESCAPED_UNICODE'?", options: ["Para forzar el cifrado seguro de contraseñas", "Para evitar caracteres raros al codificar", "Para parsear un objeto de JavaScript", "Para detectar el mensaje de error de validación"], correct: 1 },
    { q: "¿Qué métodos de JavaScript (JS) se corresponden con la codificación y decodificación de JSON?", options: ["json_encode() y json_decode()", "JSON.stringify() (de JS a JSON) y JSON.parse() (de JSON a JS)", "res.json() exclusivamente", "loadHTML() y DOMXPath()"], correct: 1 },
    { q: "En el uso moderno con FETCH y AJAX, ¿qué método de la respuesta convierte automáticamente el JSON interno?", options: ["res.parse()", "res.json() (que internamente usa JSON.parse())", "res.stringify()", "res.file_get_contents()"], correct: 1 },
    { q: "Definición de CSV (Comma-Separated Values) según el tema:", options: ["Formato para datos vectoriales donde cada objeto se encierra en llaves", "Formato para datos tabulares: cada columna se separa por una coma (,) y cada fila con un salto de línea (\\n)", "Un lenguaje de marcado matemático jerárquico", "Una directiva de protección contra el scrapeo masivo"], correct: 1 },

    // 03. GESTIÓN DE DATOS SEMI-ESTRUCTURADOS (Web Semántica y Ontologías)
    { q: "¿Qué es la Web Semántica según la definición del seno del W3C?", options: ["Un conjunto de bases de datos relacionales distribuidas en España", "Conjunto de actividades con tendencia a la creación de tecnologías para publicar datos legibles por aplicaciones informáticas", "Un buscador que penaliza el contenido duplicado con IA", "La sección de términos y condiciones de un sitio web e-commerce"], correct: 1 },
    { q: "¿Cómo se proporcionan los datos en la Web Semántica para que las máquinas los evalúen automáticamente?", options: ["En forma de archivos CSV planos", "De manera formal en forma de ONTOLOGÍAS", "Mediante expresiones regulares parametrizadas", "A través de inyecciones guiadas por booleanos"], correct: 1 },
    { q: "Definición de 'Ontología' según el texto del tema:", options: ["Una función de PHP que limpia entradas de texto peligrosas", "Descripción formal que proporciona a los usuarios humanos un conocimiento compartido sobre un dominio concreto", "Un robot indexador que recorre grafos en anchura", "Un formato más pesado que XML usado en APIs REST"], correct: 1 },
    { q: "¿Cuáles son las tres utilidades directas enumeradas de las Ontologías?", options: ["Validar emails, sanitizar strings y deshabilitar funciones", "Organizar datos, mejorar las búsquedas e integrar información", "Hacer scraping, link building y SEO on-page", "Evitar el vendor lock-in, reducir CAPEX y eliminar cookies"], correct: 1 },
    { q: "En el ejemplo de la Ontología 'Universidad', ¿qué elemento representa que ':Zerjillo' es una instancia de ':Profesor'?", options: ["Una clase abstracta", "Una instancia de clase", "Una relación de cardinalidad", "Una herencia por subclase"], correct: 1 },
    { q: "En el ejemplo de la Ontología 'Universidad', ¿qué representa ':Imparte(:Zerjillo, :SIBW)'?", options: ["Una restricción de cardinalidad", "Una relación", "Una herencia de subclase", "Una instancia de datos desestructurados"], correct: 1 },
    { q: "¿Qué ejemplo visual de Ontología en forma de árbol jerárquico con nodos como 'Veggie-Pizza' o 'Mozzarella' se incluye?", options: ["La Ontología de la Universidad", "La Ontología de la Pizza (root -> Pizza / Topping)", "La Ontología de un Curriculum Vitae", "La Ontología de Rafael Payá"], correct: 1 },
    { q: "¿Qué significan las siglas RDF?", options: ["Relational Data Format", "Resource Description Framework", "Robot Digital Finder", "Reglamento de Datos Formales"], correct: 1 },
    { q: "¿Qué es OWL según el temario?", options: ["Web Ontology Language (Lenguaje de marcado para publicar y compartir datos usando ontologías en la WWW)", "Un validador automático de sintaxis JSON", "Un método antiscraping basado en captchas", "Un algoritmo de ordenación de ranking de Google"], correct: 1 },
    { q: "El lenguaje OWL tiene como objetivo facilitar un modelo de marcado construido sobre...", options: ["Bases de datos NoSQL", "RDF y codificado en XML", "Archivos CSV y saltos de línea", "Funciones prepared statements de PHP"], correct: 1 },

    // 04. GESTIÓN DE DATOS NO ESTRUCTURADOS (Crawlers, Scraping y SEO)
    { q: "¿Cómo se denominan los robots (bots) que navegan por las webs indexando y clasificando los contenidos haciendo una búsqueda en un grafo?", options: ["Mapeadores o Traductores", "Crawlers o Spiders", "Validators o Checkers", "Scrapers de leads"], correct: 1 },
    { q: "¿Qué dos tipos de estrategias de búsqueda en grafos siguen los Crawlers?", options: ["Búsqueda lineal o binaria", "Por anchura, por profundidad o esquemas mixtos", "Búsqueda relacional o parametrizada", "In-band o a ciegas"], correct: 1 },
    { q: "Para limitar el acceso de los buscadores a ciertas partes de nuestro sitio, ¿qué archivo debemos configurar en el directorio raíz?", options: ["sitemap.xml", "robots.txt", "index.html", "descripcion.xsd"], correct: 1 },
    { q: "Si se quiere impedir con total seguridad que una página aparezca en los resultados de Google, ¿qué advierte el tema sobre robots.txt?", options: ["Que robots.txt es 100% infalible para ocultar páginas", "Advertencia: No utilices robots.txt para impedir que aparezcan; pueden acabar indexándose si otras páginas las enlazan. Usa contraseña o directiva noindex", "Que robots.txt solo funciona con archivos PDF", "Que robots.txt requiere una licencia comercial del W3C"], correct: 1 },
    { q: "¿Qué directiva exacta de metaetiqueta metida en el <head> del HTML impide que los robots indexen la página?", options: ["<meta name='robots' content='noindex'>", "<meta class='disable_functions'>", "<meta type='xs:string'>", "<meta href='robots.txt'>"], correct: 0 },
    { q: "¿Cuáles son las 4 fases consecutivas del proceso de indexación en la era de la IA?", options: ["Validación, Sanitización, Parámetros y Ejecución", "Rastreo, Procesamiento, Indexación y Clasificación/Ranking", "Scraping, Legalidad, Ofuscación y Captcha", "Keywords, On-Page, Off-Page y Link Building"], correct: 1 },
    { q: "Definición de 'Scraping' según el temario:", options: ["Un método de cifrado asimétrico para transacciones activas", "Técnica utilizada para extraer información de sitios web de manera automática y masiva", "Una ontología compleja sobre el dominio de discurso", "Un validador sintáctico de declaraciones preparadas"], correct: 1 },
    { q: "En el script PHP de scraping para buscar correos, ¿qué símbolo se antepone a '$dom->loadHTML' para evitar los mensajes de warning?", options: ["El símbolo de dólar ($)", "El símbolo de arroba (@)", "El guion bajo (_)", "La doble barra (//)"], correct: 1 },
    { q: "Para que el scraping sea totalmente legal en España, debe cumplir con:", options: ["La directiva noNamespaceSchemaLocation", "El RGPD y la LOPDGDD", "Las restricciones exclusivas de MathML", "La configuración de mysqli.max_links"], correct: 1 },
    { q: "¿Cuáles son los tres supuestos permitidos para rastrear datos personales mediante scraping?", options: ["Que sea rápido, que no gaste RAM y que se use Laravel", "Fuentes de acceso público, Interés público general (con evaluación) o bajo el Consentimiento de la persona rastreada", "Que los datos estén en formato JSON, XML o CSV relacional", "Que el archivo robots.txt no exista en el servidor de destino"], correct: 1 },
    { q: "Mencione tres de los 'Métodos antiscraping' descritos para evitar la extracción automática por bots:", options: ["Usar bases relacionales, tipar las variables y usar bind_param", "Controles de acceso (límites/bloqueos IP), Verificación de usuarios (Captchas/cookies) y Protección de contenido (honeypots/ofuscación)", "Hacer link building, optimizar la experiencia UX y rellenar palabras clave", "Eliminar el prólogo XML, quitar las entidades y reducir los sitemaps"], correct: 1 },
    { q: "Al hablar de la era actual del SEO con IA, ¿qué cambio de paradigma radical se destaca sobre las búsquedas?", options: ["Que el usuario ahora busca obligatoriamente usando código SQL", "Google ya no busca palabras... entiende lo que quieres (contexto e intención)", "El SEO ha desaparecido por completo debido a las APIs REST", "Ya solo importa la repetición masiva de palabras clave (keywords)"], correct: 1 },
    { q: "Dentro de las técnicas SEO actuales, ¿qué factor ha dejado de ser importante en la Construcción de Enlaces (Link Building)?", options: ["La autoridad del dominio de origen", "La cantidad pura de enlaces a las páginas (ahora prima la calidad/relevancia)", "El uso seguro del protocolo HTTPS", "La velocidad de carga del sitio web móvil"], correct: 1 },
    { q: "¿Qué importante advertencia ('OJO') se incluye respecto a aparecer en las respuestas directas de 'AI Overviews' de Google?", options: ["Que te harás millonario de inmediato por la publicidad", "NO GANAS CLICKS: El usuario puede obtener la respuesta directa y no entrar a tu web", "Que tu sitemap quedará obsoleto de forma automática", "Que el framework Laravel bloqueará tu base de datos"], correct: 1 },
    { q: "Como conclusión de las controversias del uso de IA en SEO, complete la idea clave del sector: 'La IA no elimina el SEO, cambia el tipo de profesional necesario...'", options: ["ahora solo se necesitan programadores de COBOL'", "SEO + IA Specialist'", "expertos en inyecciones SQL'", "administradores de servidores On-premise'"], correct: 1 }
];