var database = database || {};

database.tema4 = [
    // 01. DISEÑO WEB
    { q: "¿De qué se encarga principalmente el diseño web según el tema?", options: ["De la programación del lado del servidor", "De la apariencia visual y la estructura de un sitio web, incluyendo colores, tipografías e imágenes", "De la configuración de las directivas de robots.txt", "De la optimización de las sentencias SQL preparadas"], correct: 1 },
    { q: "¿Cuál es el objetivo principal del diseño web?", options: ["Reducir el consumo de memoria RAM en el Back-end", "Crear un sitio atractivo y coherente que refleje la identidad de la marca o propósito", "Eliminar por completo el uso de hojas de estilo CSS", "Automatizar el rastreo de los spiders de búsqueda"], correct: 1 },
    { q: "¿Qué tres disciplinas fundamentales se interconectan dentro del diseño web según las diapositivas?", options: ["Diseño Gráfico, Diseño de Interfaz (UI) y Diseño de Experiencia de Usuario (UX)", "HTML, CSS y JavaScript", "CAPEX, OPEX y Deuda Técnica", "MySQL, PHP y Apache"], correct: 0 },
    { q: "¿Cuál es la función del Diseño Gráfico en el entorno web?", options: ["Escribir código estructurado y fuertemente tipado", "Centrarse en la estética, la marca y la comunicación visual", "Definir la arquitectura de los servidores de tres capas", "Auditar la legalidad del scraping masivo"], correct: 1 },
    { q: "¿En qué se enfoca específicamente el Diseño de Interfaz (UI)?", options: ["En la gestión de la persistencia de datos", "En la disposición de los elementos interactivos, botones y pantallas con las que el usuario interactúa", "En las auditorías SEO de palabras clave", "En evitar las inyecciones de código malicioso"], correct: 1 },
    { q: "¿Cuál es la meta del Diseño de Experiencia de Usuario (UX)?", options: ["Asegurar que el proceso global sea intuitivo, agradable y eficiente para el usuario", "Reducir el coste de mantenimiento anual del dominio", "Configurar sitemaps automáticos mediante plugins", "Deshabilitar las funciones peligrosas del sistema operativo"], correct: 0 },

    // 02. USABILIDAD
    { q: "Según la definición de la ISO (9241-11), ¿qué es la usabilidad?", options: ["La velocidad en milisegundos con la que carga un archivo HTML", "El grado en que un producto puede ser usado por usuarios específicos para conseguir metas específicas con efectividad, eficiencia y satisfacción", "La capacidad de un sistema para resistir ataques de inyección SQL a ciegas", "El número total de enlaces externos que apuntan a una página web"], correct: 1 },
    { q: "En los SIBW, ¿cuál es una de las grandes realidades sobre los usuarios y la usabilidad?", options: ["Los usuarios leen detalladamente cada pantalla antes de hacer clic", "Si un sitio es difícil de usar o la información no se encuentra rápido, los usuarios se van (no hay fidelidad obligada)", "Los usuarios prefieren sistemas complejos que requieran formación previa", "La usabilidad solo importa si el sitio web es de tipo e-commerce"], correct: 1 },
    { q: "¿Cuáles son los 5 atributos de usabilidad de Jakob Nielsen citados en el tema?", options: ["Velocidad, Rendimiento, Seguridad, Escalabilidad y Redundancia", "Facilidad de aprendizaje, Eficiencia, Facilidad de recuerdo, Errores (prevención/recuperación) y Satisfacción", "CAPEX, OPEX, ROI, Van y Tir", "Rastreo, Procesamiento, Indexación, Ranking y SEO"], correct: 1 },
    { q: "¿Qué mide el atributo de 'Facilidad de aprendizaje' (Learnability)?", options: ["Cuántos errores catastróficos comete el usuario en un día", "Lo fácil que resulta para los usuarios realizar tareas básicas la primera vez que ven la interfaz", "El tiempo que tarda un desarrollador senior en entender el código Back-end", "El número de clics necesarios para comprar un producto"], correct: 1 },
    { q: "Dentro de los atributos de Nielsen, la 'Eficiencia' se define como:", options: ["La ausencia total de warnings en el servidor PHP", "Una vez aprendido el diseño, cuánto tardan en realizar las tareas", "El porcentaje de usuarios que puntúan el sitio con cinco estrellas", "El peso en kilobytes de la página de inicio"], correct: 1 },
    { q: "¿Qué evalúa el atributo de 'Facilidad de recuerdo' (Memorability)?", options: ["La cantidad de datos históricos guardados en la caché", "Cuando los usuarios vuelven al diseño tras un periodo de no usarlo, con qué rapidez restablecen su habilidad", "La longitud máxima de una URL con query strings", "La persistencia de las variables de sesión en las cookies"], correct: 1 },
    { q: "Respecto a los 'Errores' en la usabilidad, ¿qué se debe analizar?", options: ["El código de estado HTTP que devuelve el servidor web", "Cuántos errores cometen los usuarios, la gravedad de estos y la facilidad para recuperarse", "Las vulnerabilidades XSS encontradas en los formularios", "El número de enlaces rotos detectados en el sitemap"], correct: 1 },
    { q: "¿Qué es la 'Satisfacción' en el marco de los atributos de Nielsen?", options: ["El ancho de banda ilimitado proporcionado por el hosting", "Lo agradable que es el diseño de la interfaz para el usuario", "La velocidad de indexación de Googlebot", "La integración del Enterprise Service Bus"], correct: 1 },
    { q: "El temario asocia un buen diseño UX/UI con el éxito del negocio porque reduce un coste crítico. ¿Cuál?", options: ["El coste del registro del dominio de segundo nivel", "Reduce los errores de usuario y los costes de soporte/mantenimiento", "El coste operativo de contratar hosting dedicado", "Elimina la necesidad de cumplir con el RGPD"], correct: 1 },

    // 03. MÉTODOS DE DISEÑO
    { q: "¿Cuál es el enfoque central del 'Diseño Centrado en el Usuario' (DCU)?", options: ["Diseñar pensando exclusivamente en las limitaciones del hardware del servidor", "El proceso de diseño se enfoca y se guía por las necesidades, características y limitaciones de los usuarios finales", "Programar la lógica de negocio antes de definir la interfaz visual", "Utilizar la IA para automatizar la generación de todo el sitio web"], correct: 1 },
    { q: "¿En qué consiste el principio de 'Diseño Inclusivo'?", options: ["En incluir todos los frameworks de JavaScript en el proyecto", "Diseñar para la mayor diversidad de personas posible, considerando capacidades, edades y contextos sin crear soluciones separadas", "Permitir que cualquier usuario se conecte como superusuario a la BD", "Incluir contenido dinámico generado por microservicios heterogéneos"], correct: 1 },
    { q: "Definición de 'Accesibilidad Web' según los apuntes:", options: ["La posibilidad de entrar a la web mediante conexiones móviles 5G", "Asegurar que las personas con discapacidad puedan percibir, comprender, navegar e interactuar con la web", "Configurar correctamente los permisos de lectura en el servidor Linux", "La velocidad de respuesta ante peticiones asíncronas de AJAX"], correct: 1 },
    { q: "¿Qué organización desarrolla las pautas de accesibilidad web estándar?", options: ["ICANN", "W3C (a través de la Iniciativa de Accesibilidad Web - WAI)", "Googlebot AI Team", "Red.es en España"], correct: 1 },
    { q: "¿Qué significan las siglas WCAG?", options: ["Web Code Architecture Guidelines", "Web Content Accessibility Guidelines (Pautas de Accesibilidad para el Contenido Web)", "Web Connection Automatic Gateway", "Web Cost Analysis Group"], correct: 1 },
    { q: "¿Cuáles son los 4 principios fundamentales de las WCAG (POUR)?", options: ["Programable, Optimizado, Utilizable, Redundante", "Perceptible, Operable, Comprensible (Understandable) y Robusto", "Precio, Operación, Utilidad, Rendimiento", "Petición, Objeto, URL, Respuesta"], correct: 1 },
    { q: "Dentro de POUR, ¿qué exige el principio de 'Perceptible'?", options: ["Que el código HTML se valide sin fallos en el validador del W3C", "Que la información y los componentes de la interfaz de usuario deben ser mostrados en formas que puedan ser percibidos", "Que los botones cambien de color automáticamente con CSS", "Que la web funcione correctamente en dispositivos Microsoft Surface"], correct: 1 },
    { q: "¿Qué define el principio 'Operable' de las WCAG?", options: ["Los componentes de la interfaz y la navegación deben ser operables (el usuario debe poder usar los controles)", "La aplicación debe estar operativa en el servidor 24/7", "El hosting debe permitir conexiones SSH seguras", "Las consultas SQL deben ejecutarse en menos de un segundo"], correct: 0 },
    { q: "El principio 'Comprensible' (Understandable) indica que:", options: ["La documentación del código debe estar escrita en inglés técnico", "La información y la operación de la interfaz de usuario deben ser comprensibles", "Los microservicios deben entender los mensajes estructurados en JSON", "Los términos legales deben ser aceptados mediante consentimiento explícito"], correct: 1 },
    { q: "Dentro de POUR, ¿qué significa que un sistema web sea 'Robusto'?", options: ["Que tiene un coste CAPEX muy elevado", "El contenido debe ser lo suficientemente robusto para ser interpretado de forma fiable por una amplia variedad de agentes de usuario (incluyendo tecnologías asistivas)", "Que resiste ataques masivos de inyección SQL basados en errores", "Que está alojado en un centro de datos con redundancia en colocación"], correct: 1 },
    { q: "¿Cuáles son los tres niveles de conformidad de las WCAG de menor a mayor exigencia?", options: ["Bajo, Medio y Alto", "A, AA y AAA", "1 Capa, 2 Capas y 3 Capas", "Local, Nacional e Internacional"], correct: 1 },
    { q: "¿Qué es el 'Diseño Responsive' (Adaptativo)?", options: ["Un diseño que responde a las peticiones HTTP mediante verbos POST", "Técnica de diseño que busca la correcta visualización de una misma página en distintos dispositivos (ordenadores, tablets, móviles)", "Un diseño estructurado exclusivamente mediante ontologías de la pizza", "Un sistema que cambia de color según la geolocalización de la IP"], correct: 1 },
    { q: "La filosofía de diseño 'Mobile First' propone:", options: ["Desarrollar primero la aplicación de escritorio y luego comprimirla para móviles", "Diseñar y pensar la experiencia primero para dispositivos móviles y luego expandirla a pantallas más grandes", "Obligar al usuario a descargar una app nativa desde la Play Store", "Utilizar únicamente la API de geolocalización dinámica"], correct: 1 },

    // 04. ANÁLISIS DE REQUERIMIENTOS
    { q: "En el análisis de sistemas web, ¿qué diferencia hay entre Requerimientos Funcionales y No Funcionales?", options: ["Los funcionales se escriben en PHP y los no funcionales en HTML", "Los funcionales definen lo que el sistema debe HACER; los no funcionales definen CÓMO debe ser el sistema (propiedades, restricciones, rendimiento, seguridad)", "Los funcionales los define el cliente y los no funcionales el propietario legal", "Los funcionales tienen coste CAPEX y los no funcionales coste OPEX"], correct: 1 },
    { q: "La funcionalidad 'El sistema debe permitir al usuario registrarse e iniciar sesión' se clasifica como:", options: ["Requerimiento No Funcional de Seguridad", "Requerimiento Funcional", "Arquitectura de Información compleja", "Técnica SEO estratégica"], correct: 1 },
    { q: "La restricción 'La página web debe cargar en menos de 2 segundos en redes móviles' se clasifica como:", options: ["Requerimiento Funcional de rendimiento", "Requerimiento No Funcional", "Restricción de granularidad fina", "Uso de software legado"], correct: 1 },
    { q: "En la especificación de requerimientos, ¿qué es un 'Caso de Uso'?", options: ["Un ejemplo real de inyección SQL in-band", "Una descripción de los pasos o interacciones entre un actor (usuario o sistema) y el sistema para alcanzar una meta", "El balance económico entre CAPEX y OPEX de una startup", "Una auditoría para detectar problemas de accesibilidad con tecnologías asistivas"], correct: 1 },
    { q: "¿Qué técnica narrativa se utiliza comúnmente en metodologías ágiles (Scrum) para expresar requerimientos desde la perspectiva del usuario?", options: ["Casos de Uso relacionales", "Historias de Usuario (User Stories)", "Diagramas de Gantt estáticos", "Prólogos XML de marcado"], correct: 1 },
    { q: "Estructura estándar de una Historia de Usuario:", options: ["SELECT columna FROM tabla WHERE condición", "Como [tipo de usuario], quiero [acción] para [beneficio/valor]", "<xs:element name='usuario' type='string'>", "User-agent: * Disallow: /includes/"], correct: 1 },

    // 05. ARQUITECTURA DE LA INFORMACIÓN
    { q: "¿De qué se encarga la Arquitectura de la Información (AI) según el tema?", options: ["De elegir el proveedor de Cloud Hosting más barato", "De la organización, estructuración y etiquetado de los contenidos de un sitio web para facilitar que los usuarios encuentren la información", "De programar las declaraciones preparadas con bind_param()", "De controlar los permisos de los superusuarios de la base de datos"], correct: 1 },
    { q: "Dentro de la AI, ¿qué es un 'Mapa del Sitio' (Sitemap conceptual)?", options: ["Un archivo XML que lee Googlebot obligatoriamente", "Un diagrama visual que representa la estructura jerárquica de las páginas y secciones del sitio web", "Una lista ordenada de palabras clave generadas por una IA", "Un mapa geográfico interactivo de las instalaciones físicas on-premise"], correct: 1 },
    { q: "¿En qué consiste la técnica de 'Card Sorting' (Ordenación de tarjetas)?", options: ["Un método para evaluar el rendimiento de los discos duros SSD", "Un método de investigación con usuarios donde estos organizan conceptos en categorías que tengan sentido para ellos (ayuda a definir la navegación)", "Una técnica para inyectar código malicioso en pasarelas de pago", "Un juego de lógica utilizado en los descansos de los equipos de DevOps"], correct: 1 },
    { q: "¿Qué diferencia hay entre Card Sorting Abierto y Cerrado?", options: ["El abierto es gratuito y el cerrado requiere pagar licencia comercial", "En el abierto los usuarios crean sus propios nombres para las categorías; en el cerrado las categorías ya están predefinidas", "El abierto se hace con ordenadores y el cerrado obligatoriamente con tarjetas físicas de papel", "El abierto lo realizan los desarrolladores y el cerrado los usuarios finales"], correct: 1 },
    { q: "Dentro de los sistemas de navegación de la AI, ¿qué es la 'Navegación Principal'?", options: ["El historial de páginas visitadas guardado en la caché del navegador", "El menú o barra de navegación que da acceso a las secciones clave del sitio y está visible en casi todas las páginas", "El enlace externo que apunta a una tienda e-commerce aliada", "La barra de búsqueda contextual potenciada por IA"], correct: 1 },
    { q: "¿Qué función cumple el sistema de navegación de 'Migas de Pan' (Breadcrumbs)?", options: ["Indicar al usuario el tamaño en megabytes de la página actual", "Mostrar la ruta de páginas visitadas o la posición del usuario dentro de la jerarquía del sitio (ej: Inicio > Cursos > Web)", "Permitir que el crawler o spider descubra contenido nuevo", "Borrar automáticamente las transacciones abiertas inesperadas"], correct: 1 },

    // 06. DISEÑO DE LA INTERFAZ
    { q: "¿Qué es un 'Wireframe'?", options: ["Un prototipo en alta fidelidad interactivo listo para producción", "Un esquema visual de baja fidelidad que representa la estructura básica y disposición de los elementos de una página sin diseño visual", "Un cable físico que une dos servidores dedicados", "Un validador de accesibilidad WCAG"], correct: 1 },
    { q: "¿Cuál es el propósito principal de crear wireframes en las fases iniciales?", options: ["Validar el código CSS en pantallas Surface Pro 7", "Definir la estructura, la disposición del contenido y la funcionalidad antes de invertir tiempo en diseño visual o programación", "Ahorrar ancho de banda durante el hosting compartido", "Calcular el coste OPEX del equipo de soporte"], correct: 1 },
    { q: "Al avanzar en el diseño de la interfaz, ¿qué es un 'Mockup'?", options: ["Una representación estática en alta fidelidad que incluye el diseño visual completo (colores, tipografías, imágenes, estilos)", "Un script escrito en Laravel para simular una base de datos", "Un robot que hace scraping masivo de correos electrónicos", "Un diagrama relacional de casos de uso funcionales"], correct: 0 },
    { q: "¿Qué diferencia clave tiene un 'Prototipo' frente a un Wireframe o Mockup?", options: ["El prototipo es siempre gratuito", "El prototipo es interactivo o funcional, simulando el comportamiento real de la aplicación (permite hacer clics, transiciones)", "El prototipo incluye obligatoriamente sentencias SQL preparadas", "El prototipo se ejecuta únicamente en el servidor de aplicaciones"], correct: 1 },
    { q: "¿Qué herramienta moderna de diseño UI/UX se menciona visualmente en varias diapositivas del tema para prototipar?", options: ["Photoshop", "Figma", "WordPress", "Google Sites"], correct: 1 },

    // 07. EVALUACIÓN DE LA USABILIDAD
    { q: "¿Qué es la 'Evaluación Heurística' según el temario?", options: ["Un análisis automatizado de rendimiento de las consultas SQL", "Un método de inspección donde expertos evalúan la interfaz frente a principios establecidos de usabilidad (heurísticas)", "Un test de estrés de la infraestructura cloud ante picos de tráfico", "Una auditoría legal del cumplimiento del RGPD en la base de datos"], correct: 1 },
    { q: "¿Quién inventó las 10 heurísticas de usabilidad más famosas citadas en el tema?", options: ["Tim Berners-Lee", "Jakob Nielsen", "Sergio Alonso Burgos", "Little Bobby Tables"], correct: 1 },
    { q: "Heurística 1: 'Visibilidad del estado del sistema'. ¿Qué exige?", options: ["Que el código fuente HTML sea visible públicamente en el navegador", "El sistema siempre debe mantener informados a los usuarios de lo que está ocurriendo a través de comentarios apropiados en tiempo razonable", "Que el archivo robots.txt se ubique en el directorio raíz", "Que la dirección IP fija de la empresa sea pública"], correct: 1 },
    { q: "Heurística 2: 'Relación entre el sistema y el mundo real'. Significa que:", options: ["El servidor web debe estar conectado a un reloj físico real", "El sistema debe hablar el lenguaje del usuario con palabras y conceptos familiares, en lugar de términos técnicos del sistema", "La aplicación web debe funcionar idénticamente on-premise y en la nube", "Las clases de la ontología deben coincidir con entidades del discurso"], correct: 1 },
    { q: "Heurística 3: 'Control y libertad del usuario'. ¿Qué elemento requiere?", options: ["Un botón de cierre forzado del navegador web", "Los usuarios a menudo eligen funciones por error y necesitan una 'salida de emergencia' clara (ej. deshacer, rehacer) sin diálogos extensos", "Que el usuario pueda modificar los datos tipados de la base de datos", "Un login exclusivo como superusuario"], correct: 1 },
    { q: "Heurística 4: 'Consistencia y estándares'. Propone que:", options: ["Los desarrolladores deben programar usando siempre el mismo lenguaje", "Los usuarios no deberían tener que preguntarse si diferentes palabras, situaciones o acciones significan lo mismo. Sigue las convenciones", "Todos los archivos JSON deben usar comillas simples", "La web debe verse igual solo en pantallas móviles de baja resolución"], correct: 1 },
    { q: "Heurística 5: 'Prevención de errores'. ¿Qué es mejor que un buen mensaje de error?", options: ["Un sistema de logs que registre los fallos internamente", "Un diseño cuidadoso que prevenga que ocurra el problema en primer lugar", "Una declaración try/catch asíncrona en JavaScript", "Una función filter_var de sanitización automática"], correct: 1 },
    { q: "Heurística 6: 'Reconocimiento antes que recuerdo'. ¿Qué directriz plantea?", options: ["Que la caché de historial guarde todas las páginas visitadas", "Minimizar la carga de memoria del usuario haciendo visibles los objetos, acciones y opciones (el usuario no debe recordar información de una parte a otra)", "Utilizar imágenes SVG de alta definición para captar la atención", "Hacer que el menú principal desaparezca en las subpáginas"], correct: 1 },
    { q: "Heurística 7: 'Flexibilidad y eficiencia de uso'. ¿Qué elementos benefician a los usuarios expertos?", options: ["Los captchas y controles de acceso IP obligatorios", "Los aceleradores o atajos (invisibles para usuarios novatos) que permiten hacer acciones más rápido", "Los sitemaps conceptuales complejos de estructura gruesa", "Las respuestas directas en texto plano de AI Overviews"], correct: 1 },
    { q: "Heurística 8: 'Diseño estético y minimalista'. ¿Qué contenido debe evitarse?", options: ["Los componentes gráficos desarrollados en Figma", "Los diálogos no deben contener información irrelevante o raramente necesitada; cada unidad extra de información compite y disminuye la visibilidad", "Las hojas de estilo CSS adaptativas", "Los subdominios en la URL del Dominio de Segundo Nivel"], correct: 1 },
    { q: "Heurística 9: 'Ayudar a los usuarios a reconocer, diagnosticar y recuperarse de los errores'. Los mensajes de error deben:", options: ["Mostrar códigos hexadecimales complejos del volcado de memoria", "Estar expresados en un lenguaje claro (sin códigos técnicos), indicar el problema con precisión y sugerir una solución constructiva", "Ser enviados automáticamente al Contacto de Facturación por correo", "Redirigir inmediatamente al index.html del sitio web público"], correct: 1 },
    { q: "Heurística 10: 'Ayuda y documentación'. Aunque es mejor que el sistema se use sin ayuda, si es necesaria esta debe:", options: ["Tener longitud infinita y estar estructurada en un DTD abstracto", "Ser fácil de buscar, enfocada en las tareas del usuario, listar pasos concretos y no ser demasiado grande", "Estar oculta tras una contraseña de superusuario", "Estar enlazada en los comentarios del archivo robots.txt"], correct: 1 },
    { q: "Al realizar evaluaciones de usabilidad, ¿qué es un 'Test con Usuarios'?", options: ["Una encuesta de opinión enviada por correo electrónico al terminar el año", "Prueba empírica donde usuarios reales realizan tareas asignadas en la interfaz mientras observadores registran dificultades, errores y tiempos", "Un script automático que simula miles de clics por segundo", "Un análisis de la autoridad del dominio basado en backlinks"], correct: 1 },
    { q: "En los tests con usuarios, ¿en qué consiste la técnica de 'Pensamiento en Voz Alta' (Think Aloud)?", options: ["En que los desarrolladores debatan los requerimientos gritando", "Se pide a los usuarios que expresen verbalmente sus pensamientos, dudas y sentimientos de forma continua mientras realizan las tareas", "En dictar las contraseñas al sistema mediante comandos de voz", "En reproducir archivos de audio explicativos en streaming de baja latencia"], correct: 1 },
    { q: "Para capturar de forma visual el recorrido ocular de un usuario por la pantalla de la interfaz, se utiliza la tecnología de:", options: ["Card Sorting interactivo", "Seguimiento Ocular (Eye Tracking / Mapas de calor)", "Wireframes de alta fidelidad", "Auditorías SEO técnicas automáticas"], correct: 1 },
    { q: "¿Qué representa un 'Mapa de Calor' (Heatmap) en una evaluación de interfaz?", options: ["Las zonas del servidor que consumen más energía eléctrica", "Las áreas de la pantalla donde los usuarios fijan la mirada o hacen clic con mayor frecuencia (zonas rojas/calientes)", "Las páginas web con mayor tasa de inyecciones de código malicioso", "Los países de origen de los ciberataques según el registro WHOIS"], correct: 1 },

    // 08. COSTES EN DISEÑO Y USABILIDAD
    { q: "¿Cómo se justifica económicamente la inversión inicial (CAPEX) en usabilidad según el tema?", options: ["Garantiza que el precio anual del dominio de segundo nivel se reduzca", "Evita tener que rediseñar el sistema en fases avanzadas, lo cual es exponencialmente más caro, y disminuye costes OPEX de soporte", "Elimina por completo el pago de servidores cloud elásticos", "Permite prescindir de profesionales especializados en SEO y marketing"], correct: 1 },
    { q: "Según los datos de costes presentados, ¿qué porcentaje de los problemas de usabilidad puede detectar un grupo de 5 evaluadores expertos en una evaluación heurística?", options: ["Menos del 20%", "Alrededor del 75% - 80% de los problemas principales", "El 100% de forma infalible sin requerir tests con usuarios reales", "Exactamente el mismo porcentaje que una auditoría automática con IA"], correct: 1 },

    // 09. DARK PATTERNS (Patrones engañosos)
    { q: "¿Qué es un 'Dark Pattern' (Patrón engañoso) según la sección de usabilidad del tema?", options: ["Un error de programación que rompe el árbol DOM de la página", "Interfaces de usuario diseñadas deliberadamente para engañar o manipular a los usuarios para que realicen acciones que benefician a la empresa", "Un estilo CSS con fondo negro para ahorrar batería en móviles", "Un robot crawler malicioso que suplanta la identidad de Googlebot"], correct: 1 },
    { q: "Al contrastar principios, ¿en qué se diferencia el 'Diseño Persuasivo' de un 'Dark Pattern'?", options: ["El diseño persuasivo ayuda al usuario y es transparente; el Dark Pattern beneficia solo a la empresa y es engañoso", "El Dark Pattern es ético y el diseño persuasivo es manipulativo", "No hay diferencias, son sinónimos comerciales dentro del marketing digital", "El diseño persuasivo requiere bases NoSQL y el Dark Pattern bases relacionales"], correct: 0 },
    { q: "¿Qué sitio web de referencia mundial se cita textualmente como denuncia pública ('Hall of Shame') de Dark Patterns?", options: ["https://www.deceptive.design", "https://www.xkcd.com", "https://www.w3.org/WAI", "https://www.xml-sitemaps.com"], correct: 0 },
    { q: "Dark Pattern 1: 'Roach Motel' (Trampa para cucarachas). ¿En qué consiste?", options: ["En que la página web tarda mucho en cargar y se queda congelada", "La situación en la que es muy fácil entrar o suscribirse a un servicio, pero extremadamente difícil o confuso darse de baja", "Inyectar código malicioso a través de un campo de texto de login", "Mostrar anuncios emergentes gigantes que ocultan el menú principal"], correct: 1 },
    { q: "Dark Pattern 2: 'Sneak into Basket' (Colar en el carrito). Significa que:", options: ["El sistema borra tus productos elegidos al refrescar la página", "El sitio web añade automáticamente un producto extra o servicio opcional (como un seguro) al carrito sin tu consentimiento explícito", "El crawler o spider recopila tus datos de compra de forma masiva", "Las cookies de sesión guardan artículos duplicados de forma inesperada"], correct: 1 },
    { q: "Dark Pattern 3: 'Hidden Costs' (Costes ocultos). Ocurre cuando:", options: ["El proveedor de hosting te cobra extras por el tráfico consumido", "Los costes reales del producto o tasas adicionales se ocultan hasta el último paso del proceso de pago de la compra", "La deuda técnica acumulada por malas decisiones de programación supera el CAPEX", "El precio del dominio aumenta al cambiar de agente registrador"], correct: 1 },
    { q: "Dark Pattern 4: 'Confirmshaming'. Consiste en:", options: ["Obligar al usuario a validar su correo electrónico tres veces", "Utilizar un lenguaje manipulador o de culpabilidad en los botones de rechazo para hacer sentir mal al usuario si no elige la opción comercial", "Denunciar públicamente a las webs lentas en el Hall of Shame", "Bloquear la dirección IP del usuario mediante métodos antiscraping"], correct: 1 },
    { q: "Dark Pattern 5: 'Disguised Ads' (Anuncios disfrazados). Ocurre cuando:", options: ["Los anuncios se ocultan detrás de las imágenes de fondo SVG", "Los anuncios publicitarios están diseñados para parecer contenido editorial, botones de descarga o enlaces de navegación legítimos del sitio", "El archivo robots.txt prohíbe el rastreo de banners comerciales", "La IA genera meta descripciones engañosas para inflar el SEO"], correct: 1 },
    { q: "Dark Pattern 6: 'Forced Continuity' (Continuidad forzada). ¿Cómo opera?", options: ["El bucle do...while se ejecuta de forma infinita en JavaScript", "Tras finalizar un periodo de prueba gratuito, se empieza a cobrar automáticamente la suscripción sin un aviso claro ni cancelación sencilla", "Las conexiones persistentes permanecen abiertas bloqueando la base de datos", "El microservicio comparte obligatoriamente la base de datos centralizada"], correct: 1 },
    { q: "Dark Pattern 7: 'Friend Spam'. Se define como:", options: ["Un ataque de denegación de servicio lanzado por usuarios descontentos", "El producto solicita permisos de acceso a tus contactos (redes, e-mail) bajo un pretexto falso y luego les envía spam masivo en tu nombre", "Un foro anime donde los bots publican miles de comentarios no deseados", "Hacer scraping de leads de posibles clientes de forma ilegal"], correct: 1 },
    { q: "Dark Pattern 8: 'Bait and Switch' (Señuelo y cambio). Ocurre cuando:", options: ["El usuario intenta cambiar su contraseña y el sistema da error", "El usuario realiza una acción esperando un resultado concreto (ej. cerrar una ventana), pero el sistema ejecuta una acción completamente diferente", "Se migra una base de datos relacional de MySQL a PostgreSQL", "Se traduce una URL amigable a una dirección IP de 128 bits"], correct: 1 },
    { q: "Dark Pattern 9: 'Hidden Legals' (Legales ocultos). Consiste en:", options: ["Ocultar los archivos de configuración PHP en carpetas de sistema", "Esconder cláusulas críticas o condiciones abusivas dentro de textos gigantescos y menús de difícil acceso", "Realizar scraping masivo sin cumplir con la normativa de la LOPDGDD", "No registrar de forma oficial el nombre del Titular en WHOIS"], correct: 1 },
    { q: "Dark Pattern 10: 'Trick Questions' (Preguntas con trampa). Operan mediante:", options: ["Formularios complejos escritos en MathML matemático", "El uso de casillas de verificación (checkboxes) con redacciones confusas o lógicas inversas para que marques opciones sin querer", "Declaraciones preparadas que contienen errores sintácticos voluntarios", "Consultas booleanas a ciegas realizadas por atacantes"], correct: 1 },
    { q: "Dark Pattern 11: 'Privacy Zuckering'. Se denomina así en honor al fundador de Facebook y consiste en:", options: ["Robar contraseñas mediante inyección de código XSS", "Manipular la interfaz mediante configuraciones confusas para que el usuario comparta públicamente más datos personales de los que desea", "Almacenar archivos PDF libres en sistemas on-premise inseguros", "Configurar el servidor Apache en el puerto estándar 80 sin HTTPS"], correct: 1 },
    { q: "Dark Pattern 12: 'Price Comparison Prevention' (Prevención de comparación de precios). Ocurre cuando:", options: ["Los scrapers de la competencia sufren bloqueos automáticos de IP", "El sitio web dificulta o imposibilita comparar el precio de un artículo con otros similares para que no sepas cuál es la opción más barata", "Se calculan mal los porcentajes de IVA mediante el operador '%'", "El Cloud Hosting altera el coste de las llamadas elásticas en tiempo real"], correct: 1 },
    { q: "Dark Pattern 13: 'Scarcity / Urgency' (Escasez o urgencia falsa). Consiste en:", options: ["Restringir los sitemaps de la web personal a solo 4 páginas", "Mostrar contadores de tiempo falsos o mensajes del tipo '¡Solo queda 1 artículo disponible!' para forzar una decisión de compra rápida", "Limitar el número de enlaces con bind_param() en PHP", "Utilizar la directiva disable_functions para recortar recursos de red"], correct: 1 },
    { q: "Dark Pattern 14: 'Misdirection' (Desvío de atención). Se define como:", options: ["Redirigir las peticiones HTTP del puerto 80 al puerto 443 seguro", "Enfocar la atención del usuario en un elemento visual atractivo para camuflar otra acción que conlleva costes o pérdida de derechos", "Una mala enrutación de paquetes IP en la capa de internet", "La llamada a servicios compuestos heterogéneos de granularidad gruesa"], correct: 1 },

    // 10. CONCLUSIONES DEL TEMA
    { q: "Como gran conclusión sobre el diseño web centrado en el usuario, complete la siguiente premisa: 'La usabilidad no es solo diseño visual: es...'", options: ["optimización pura del motor de base de datos relacional'", "comprensión del comportamiento humano'", "la escritura de historias de usuario en Scrum'", "el uso de herramientas automatizadas de prototipado como Figma'"], correct: 1 },
    { q: "¿En qué momentos del ciclo de desarrollo de un SIBW debe realizarse la evaluación de la usabilidad de forma ideal?", options: ["Únicamente en el despliegue final una vez lanzado el producto", "Debe realizarse de manera continua durante todo el ciclo de diseño y desarrollo", "Solo si el cliente detecta fallos graves y emite una queja formal", "Únicamente antes de calcular el presupuesto inicial (CAPEX)"], correct: 1 }
];